### ISSUE TITLE
Memory usage reporting does not seem to be correct

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#10]
## Description
Memory usage is not consistent with the `top` or `free` commands

## Steps to Reproduce
The memory tab displays memory "**Used**" around 8.5 GB. However, `gnome-system-monitor` and the `top` and `free` commands output something around 5.1 GB.

## Screenshots

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/1a7321d1-79d9-49e0-89c1-99cdaf199f80)

## Environment

- **Astra Monitor Version**: 2
- **GNOME Version**: 45.2
- **Operating System and Version**: Ubuntu 23.10
- **Other Relevant System Information**: Kernel  6.5.0-14-generic 

## Additional Context

`top` output:
```
MiB Mem :  23911.9 total,  15140.7 free,   5237.8 used,   4070.7 buff/cache     
MiB Swap:  12288.0 total,  12288.0 free,      0.0 used.  18674.1 avail Mem 

```
`free -mt` output:
```
               total        used        free      shared  buff/cache   available
Mem:           23911        5241       15136         153        4070       18670
Swap:          12287           0       12287
Total:         36199        5241       27424

```

`head /proc/meminfo` output:
```
MemTotal:       24485780 kB
MemFree:        15494072 kB
MemAvailable:   19112260 kB
Buffers:          203044 kB
Cached:          3801784 kB
SwapCached:            0 kB
Active:          6292648 kB
Inactive:        1792248 kB
Active(anon):    4167104 kB
Inactive(anon):    69744 kB
```
I think, the correct calculation for "**Memory Used**" should be `MemTotal - MemAvailable` from `/proc/meminfo`.

Note: The above outputs were taken in different times, so they may have taken slightly different measurements.

**PS:** Thank you for creating such a wonderful extension! :) :1st_place_medal:

**Comment by lepa22** [comment]
We seem to have reported the same issue: https://github.com/AstraExt/astra-monitor/issues/9

**Comment by fedkad** [comment]
> We seem to have reported the same issue: #9

Yes. But, AFAIU you advise to display only (?) the "Active" memory metric. However, I insist in displaying the "Used" memory, which more common among the utilities I mentioned. We should also realize that there is a terminology inconsistency as it is right now.

**Comment by ljuzig** [comment]
Thank you for your suggestion. Categorizing and choosing the appropriate terminology to use when speaking about memory can be a bit tricky because many tools interchange used memory with active memory or other configurations. I chose to use linux kernel terminology, if you run `cat /proc/meminfo` you will see that the values displayed follow the correspective ones provided by the command.
However I agree that the current choice for "used memory" can be deceiving, other tools like iStat Menus add other graphs like Memory Pressure to make that more clear. I have already on the list anyway to add a way for the user to customize how they prefer to display memory so as to suit all flavors, and ofc change the default behavior which is very deceiving right now.

**Comment by ljuzig** [comment]
Ok that was a bug, I [commented](https://github.com/AstraExt/astra-monitor/blob/a43a1ecf971cb90520e422323d33ecc05874a64d/src/memory/memoryMonitor.js#L203C58-L203C58) part of the formula to make some tests and I forgot to restore it. There was a _TODO_ to add customization for the formula.
The correct formula anyway is `MemTotal - MemFree - Buffers - Cached` which is fairly similar value than `Active` but very different on the concept. I will anyway add a settings to change the formula on request.

**Comment by fedkad** [comment]
Thanks for the quick reply. I think a consistency in terminology with (at least) `gnome-system-monitor` is needed. Because this is the application you start when the user clicks the bottom - left icon on the memory tab.

I just tested on my system by stressing RAM. Some "Memory Used" percentages as reported and graphed (first column by `gnome-system-monitor`, second column by  your extension):
42% 52%
66% 76%
71% 81%  
77% 91%  
84% 99%  
87% 99%  

Note: I have just started using your extension and it looks very promising. I think it is going to replace any of the similar "system monitoring" extensions in the near future! Thanks a lot! 👏

**Comment by ljuzig** [comment]
Should be fixed with the last commit, but you will have to wait for the next release, or manually install this version:
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/13927855/monitor%40astraext.github.io.shell-extension.zip)
