### ISSUE TITLE
Possible Data Unit inconsistency under Storage

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#103]
## Steps to Reproduce

1. Run Astra Monitor version 19.
2. Select "**Data Unit: KiB/s**" under **Storage** Settings.
3. Click on Storage and move the mouse over _Global Read / Write_.
4. _Global Read_ and _Global Write_ values are displayed in **KiB/s**; however, the _Read_ and _Write_ values in the **Total Activity** pop-up are in **KB**.
5. The same inconsistency is present in the **Total Device Activity** under **Devices**.
6. (Any disk Size, Available Space, Used Space, etc. under **Devices** are displayed in KB (GB) also, but this may be done on purpose and is acceptable.)

## Screenshots
![image](https://github.com/AstraExt/astra-monitor/assets/113997707/aea83fa0-37a9-4dbb-b464-9eda35f3d391)

## Environment

- **Astra Monitor Version**: 19
- **GNOME Version**: 45.2
- **Operating System and Version**: Ubuntu 23.10
- **Other Relevant System Information**:

## Additional Context
I haven't checked, but a similar thing may apply to the **Network** menu too.

**Comment by ljuzig** [comment]
Just out of curiosity, why are you using Topbar Theme Style as Light on AstraMonitor while you have black Topbar Panel? It hurts readability of values in the main popup menu, so I wonder if there is a reason behind it.
Beside that, I'm gonna check the issue and fix it soon, thank you!

**Comment by ljuzig** [comment]
I'm not sure whether I should convert also the other units. The setting for data unit is a unit of speed (KiB/s). If you want to see data read/write in KiB/s that doesn't mean you also want to see disk space in KiB. Maybe we need another setting for that!?

**Comment by fedkad** [comment]
> Just out of curiosity, why are you using Topbar Theme Style as Light on AstraMonitor while you have black Topbar Panel? It hurts readability of values in the main popup menu, so I wonder if there is a reason behind it. Beside that, I'm gonna check the issue and fix it soon, thank you!

Actually, there is very little visual difference (mostly in the graphs) between the two _themes_:

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/19ed3fc0-23f3-48ac-ab1e-114e802f18bf)

I think, more detailed theme configurability will be needed in the future; but this is for another issue.

**Comment by fedkad** [comment]
> I'm not sure whether I should convert also the other units. The setting for data unit is a unit of speed (KiB/s). If you want to see data read/write in KiB/s that doesn't mean you also want to see disk space in KiB. Maybe we need another setting for that!?

Disk space (capacity) information may be left in KB (as I said in step no 6 above). And this will be consistent with most storage providers use this unit too.

However, IMHO, the information in **Total Activity** should be consistent with the speed unit selected by the user in the **Storage** → **Data Unit** setting.

**Comment by ljuzig** [comment]
I'm not really sure about this. If an user chooses Megabit/s as speed in network monitor do they really want the overall network activity in Megabit?

**Comment by ljuzig** [comment]
I'm closing this stale issue. Nobody else really complain so I guess this is a very edge case.
