### ISSUE TITLE
Partition Info label in Storage menu not center-aligned

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#107]
## Description

The _Partition Info_ label in the _Devices_ popup of the _Storage_ menu is not center-aligned.

## Steps to Reproduce

1. Install and enable the extension.
2. Click the _Storage_ item in the top bar.
3. Hover over an item in the _Devices_ section.
4. Observe that all section labels in the popup are center-aligned except for the _Partition Info_ label.

## Screenshots

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/b74527ab-cb54-4131-ad65-7922d0cad523)

## Environment

-   **Astra Monitor Version**: 19 (EGOv30)
-   **GNOME Version**: 45.5
-   **Operating System and Version**: Fedora 39 Workstation

**Comment by ljuzig** [comment]
Fixed, thank you!
