### ISSUE TITLE
Public IP in Network menu is not updated immediately after a change

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#108]
## Description

When the system changes its public IP(s), this is not reflected in the **Network** menu immediately.

## Steps to Reproduce

1. While AstraMonitor is running connect to a VPN service (I am testing with _WireGuard_).
2. The new public IP(s) that are obtained by the system are not reflected in the **Network** menu _immediately_ (it takes a few minutes).
3. Disconnect from the VPN service.
4. The VPN public IP(s) stay _for a while_ in the **Network** menu.

## Environment

-   **Astra Monitor Version**: 19
-   **GNOME Version**: 45.2
-   **Operating System and Version**: Ubuntu 23.10 
-   **Other Relevant System Information**: Notebook computer

## Additional Context

Restarting AstraMonitor immediately updates the **Public IP** address(es) displayed in the **Network** menu.

An explanation on the **Public IP** discovery process may be useful here.

**Comment by ljuzig** [comment]
There's no way to know when the remote IP changes. I cannot query it too often because that would be an unwanted behavior for most users. I can anyway do something about it. I can query it when the menu is opened if it hasn't been queried recently and I can add a click to refresh over the IP menu element.

**Comment by fedkad** [comment]
Personally I don't think that a public IP is something that needs to be monitored. So, the "on-demand" refresh may be an acceptable option.
