### ISSUE TITLE
Network IO Speed vertical layout is oversized

### ISSUE THREAD

**Issue by mcmxcdev** [AstraExt/astra-monitor#109]
## Description

Network IO Speed vertical layout is overlapping the top bar.
 
This wasn't an issue with Astra Monitor v18 afaik, so must have been a regression in v19.

## Steps to Reproduce

1. open extension settings
2. go to "Network" tab
3. go to "Header" > "IO"
4. enable "Show IO Speed"
5. chose "IO Speed Layout" > "Vertical"

## Screenshots

Showcasing toggling between vertical and horizontal layout for IO Speed:

[Screencast from 2024-04-13 10-19-46.webm](https://github.com/AstraExt/astra-monitor/assets/16797721/53563fce-c1a5-49cc-a5e8-10adca3dba53)

## Environment

-   **Astra Monitor Version**: 19
-   **GNOME Version**: 45.2
-   **Operating System and Version**: Ubuntu 23.10
-   **Other Relevant System Information**:

**Comment by ljuzig** [comment]
I can't reproduce that:
[Screencast from 2024-04-14 15-28-15.webm](https://github.com/AstraExt/astra-monitor/assets/11982322/ec48cfa4-1242-4c35-86ac-244f109b20c3)

Where have you downloaded the extension from? [EGO](https://extensions.gnome.org), [Github Releases](https://github.com/AstraExt/astra-monitor/releases) or built from source?

Are you able to test main branch if the problem still occurs or alternatively this build?
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/14971169/monitor%40astraext.github.io.shell-extension.zip)

Do you have any particular extension I should acknowledge like Dash to Panel or anything else that changes GNOME's top panel? What's your setting on Astra Monitor in General -> Headers -> Headers Height? Can you try to change that and see if the problem still occurs?

Thank you!

**Comment by mcmxcdev** [comment]
Very strange, now I also can't reproduce it anymore!

Probably got fixed by a laptop restart. I will close this and worse case reopen if I can find a repro case for it.
