### ISSUE TITLE
Memory and storage bars are oversized, sticking out of the bottom of the panel

### ISSUE THREAD

**Issue by aquatix** [AstraExt/astra-monitor#110]
## Description

The bars showing information about the memory usage and storage are for some reason offset to the bottom, extending out of the bottom of the panel.

## Steps to Reproduce

1. Install the extension.
2. Look at the default bars in the panel.

## Screenshots

![Screenshot from 2024-04-14 11-30-50](https://github.com/AstraExt/astra-monitor/assets/629545/d006051a-1e7e-4e4e-8835-1b11d3cb28d2)

![Screenshot from 2024-04-14 11-36-05](https://github.com/AstraExt/astra-monitor/assets/629545/82acd368-7856-4f56-b3ae-086386b3b1cc)

## Environment

-   **Astra Monitor Version**: 19 (EGOv30)
-   **GNOME Version**: 46 (also happens on 45)
-   **Operating System and Version**: Ubuntu Gnome 24.04 (also on 23.10).
-   **Other Relevant System Information**: happens on default Adwaita theme and also on others.

## Logs

n/a

## Additional Context

Please let me know if I need to provide more info and/or can help testing.

**Comment by ljuzig** [comment]
Today I tried to take a look into this but I can't reproduce this problem. Do you have any other extension that modify the gnome's top panel like `Dash to Panel` or a particular theme? Any additional info could be really helpful.
Can you provide a video screencast when enabling the Astra Monitor extension to check the behaviour and understand what might cause that? Thank you!

**Comment by aquatix** [comment]
You raise an excellent point and of course I have some other extensions that alter the top panel. Not so drastically as `Dash to Panel`, but I have some things like `Blur my Shell`, [`Gnome 4x Improvements](https://extensions.gnome.org/extension/4158/gnome-40-ui-improvements/), [`Transparent Top Bar`](https://extensions.gnome.org/extension/3960/transparent-top-bar-adjustable-transparency/) and [`Unite`](https://extensions.gnome.org/extension/1287/unite/).

However, I disabled all of those (without uninstalling them) and even after logging out and back in again, re-enabling Astra Monitors shows the bars dropping down the panel.


This is currently my extensions list (not all of them are normally enabled):

![Screenshot 2024-04-15 at 21-13-56 Installed Extensions - GNOME Shell Extensions](https://github.com/AstraExt/astra-monitor/assets/629545/e5a5b201-d4ee-474b-ad03-0bb65c05085d)

I'll try to make a screen recording too.

**Comment by aquatix** [comment]
With 'User Themes' also disabled (so everything in the above list disabled), I enabled Astra Monitor again, with this result:

https://github.com/AstraExt/astra-monitor/assets/629545/9fec4fa2-3729-4c15-83e9-f4cff51d1c8d

**Comment by aquatix** [comment]
I hope this helps :/

Thanks for your time!

**Comment by aquatix** [comment]
@diegopvlk that's an excellent observation and one that I didn't even think about 🫤

I indeed have this issue on a 4k laptop at 200% scaling. Will try on 100% to verify.

**Comment by aquatix** [comment]
I just verified and setting scaling to 200% shows the issue, while setting it to 100% makes the bars behave.

**Comment by ljuzig** [comment]
The issue lies somewhere else. I have a 4k screen with 200% scaling but I don't experience this issue (see screenshot). Are you on xorg or wayland? I may need to create a custom build that prints some logs to understand what's going on there.
I'm on the newer v20 which is not yet approved in extensions.gnome.org anyway, might worth to try it.

![Screenshot from 2024-04-19 16-29-52](https://github.com/AstraExt/astra-monitor/assets/11982322/f57577b0-9d5b-4e82-93b6-b84b70e3ebf3)

**Comment by ljuzig** [comment]
> @ljuzig interesting, this is what happens for me on v20 (both xorg and wayland):

Very interesting indeed. That looks like a VM, what distro is it? Do you have easy instructions on how to reproduce that?

**Comment by ljuzig** [comment]
Ok, I got the bug. If you notice my screenshot and yours, the scale selector is different. That's because I have mutter's `scale-monitor-framebuffer` enabled. I can see the bug too disabling that!

![Screenshot from 2024-04-19 19-32-51](https://github.com/AstraExt/astra-monitor/assets/11982322/725ebbf6-5eff-497f-b03f-19cb134e6bce)

**Comment by ljuzig** [comment]
I issued a [new release](https://github.com/AstraExt/astra-monitor/releases/tag/v21), please test it and share a feedback!
Thank you!

**Comment by aquatix** [comment]
Yes, that seems to have done the trick, thanks! Looking great 😎
