### ISSUE TITLE
Blank space when using horizontal sensors with fan speed

### ISSUE THREAD

**Issue by awumii** [AstraExt/astra-monitor#111]
## Description

This happens when one of the sensors is set to show fan speed. After the fan speed returns to idle (0 RPM), there appears a blank space between the icon and the sensors. This blank space eventually disappears after some time (if refresh frequency is 1 second, it takes around 20 seconds, but with the default refresh frequency of 3 seconds, it takes 1 minute and 30 seconds to fix itself). And the cycle repeats itself when fans spin again.

## Steps to Reproduce

1. Set the second (or the first) sensor to fan speed, and set layout to horizontal. (Screenshot 1)
2. Make fans spin. (Screenshot 2)
3. Wait for fans to stop spinning. (Screenshot 3)

## Screenshots

This is how it looks when the extension is restarted, or the sensor is changed (or the layout fixed itself like mentioned above) AND fans are idle (looks fine)
![Zrzut ekranu z 2024-04-14 23-08-24](https://github.com/AstraExt/astra-monitor/assets/29680081/02f6c53f-c30f-41e4-a400-06dade9f99e2)

This is how it looks when fans spin (also fine)
![Zrzut ekranu z 2024-04-14 23-03-50](https://github.com/AstraExt/astra-monitor/assets/29680081/dad68c76-471c-41d8-85a4-e20a2aa21e1d)

This is how it looks after the fans stop spinning (looks wrong)
![Zrzut ekranu z 2024-04-14 23-04-02](https://github.com/AstraExt/astra-monitor/assets/29680081/c21f18f3-0b03-4c37-af52-22af63f25093)

Extension settings
![Zrzut ekranu z 2024-04-14 23-41-44](https://github.com/AstraExt/astra-monitor/assets/29680081/95dfc44e-b916-4fc4-bda4-f772bfeec4d2)
![Zrzut ekranu z 2024-04-14 23-41-59](https://github.com/AstraExt/astra-monitor/assets/29680081/4acdaa37-6a07-405a-b78e-eb6623d2ce8b)
![Zrzut ekranu z 2024-04-14 23-42-50](https://github.com/AstraExt/astra-monitor/assets/29680081/5781b728-d483-4abd-aafc-e72878a0a3f2)

## Environment

-   **Astra Monitor Version**: 19 (EGOv30)
-   **GNOME Version**: 46
-   **Operating System and Version**: Arch Linux
-   **Other Relevant System Information**:

## Logs

<details>
<summary>sensors output when fans are idle</summary>
dell_smm-virtual-0
Adapter: Virtual device
Processor Fan:      0 RPM  (min =    0 RPM, max = 4700 RPM)
Motherboard Fan:    0 RPM  (min =    0 RPM, max = 4700 RPM)
CPU:              +63.0°C  
SODIMM:           +38.0°C  
Ambient:          +50.0°C  

amdgpu-pci-0600
Adapter: PCI adapter
vddgfx:        1.43 V  
vddnb:       949.00 mV 
edge:         +48.0°C  
PPT:          14.00 W  

nvme-pci-0500
Adapter: PCI adapter
Composite:    +31.9°C  (low  =  -0.1°C, high = +82.8°C)
                       (crit = +84.8°C)
Sensor 1:     +31.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +35.9°C  (low  = -273.1°C, high = +65261.8°C)

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +53.0°C  

zenpower-pci-00c3
Adapter: PCI adapter
SVI2_Core:   869.00 mV 
SVI2_SoC:    950.00 mV 
Tdie:         +65.4°C  (high = +95.0°C)
Tctl:         +65.4°C  
SVI2_P_Core:   2.86 W  
SVI2_P_SoC:    2.52 W  
SVI2_C_Core:   3.29 A  
SVI2_C_SoC:    2.35 A  

nvme-pci-0200
Adapter: PCI adapter
Composite:    +29.9°C  (low  =  -0.1°C, high = +82.8°C)
                       (crit = +84.8°C)
Sensor 1:     +29.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +34.9°C  (low  = -273.1°C, high = +65261.8°C)

BAT1-acpi-0
Adapter: ACPI interface
in0:          12.71 V  
curr1:       256.00 mA 
</details>

<details>
<summary>sensors output when fans are spinning</summary>
dell_smm-virtual-0
Adapter: Virtual device
Processor Fan:   2800 RPM  (min =    0 RPM, max = 4700 RPM)
Motherboard Fan: 2500 RPM  (min =    0 RPM, max = 4700 RPM)
CPU:              +66.0°C  
SODIMM:           +38.0°C  
Ambient:          +50.0°C  

amdgpu-pci-0600
Adapter: PCI adapter
vddgfx:        1.42 V  
vddnb:       949.00 mV 
edge:         +49.0°C  
PPT:          17.00 W  

nvme-pci-0500
Adapter: PCI adapter
Composite:    +30.9°C  (low  =  -0.1°C, high = +82.8°C)
                       (crit = +84.8°C)
Sensor 1:     +30.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +35.9°C  (low  = -273.1°C, high = +65261.8°C)

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +52.0°C  

zenpower-pci-00c3
Adapter: PCI adapter
SVI2_Core:   869.00 mV 
SVI2_SoC:    950.00 mV 
Tdie:         +65.6°C  (high = +95.0°C)
Tctl:         +65.6°C  
SVI2_P_Core:   3.43 W  
SVI2_P_SoC:    2.24 W  
SVI2_C_Core:   4.61 A  
SVI2_C_SoC:    2.35 A  

nvme-pci-0200
Adapter: PCI adapter
Composite:    +29.9°C  (low  =  -0.1°C, high = +82.8°C)
                       (crit = +84.8°C)
Sensor 1:     +29.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +36.9°C  (low  = -273.1°C, high = +65261.8°C)

BAT1-acpi-0
Adapter: ACPI interface
in0:          12.60 V  
curr1:         0.00 A 
</details>  
  
## Additional Context  

Not using any custom gtk or shell theme, only changed accent color.
Changing sensors to [lm-sensors] gives identical results.
Sometimes the sensors menu doesn't show anything, but that's probably a separate issue.
![obraz](https://github.com/AstraExt/astra-monitor/assets/29680081/5d481394-31d8-42a2-9b0d-bb5c78fe3b3d)

**Comment by ljuzig** [comment]
Yeah, we can definitely improve that! I'm gonna work on it before the release of V20.
