### ISSUE TITLE
Confusion about version numbers

### ISSUE THREAD

**Issue by hsiktas** [AstraExt/astra-monitor#113]
Here on GitHub, I can see that Beta v21 is the [latest release.](https://github.com/AstraExt/astra-monitor/releases).
But on [extensions.gnome.org](https://extensions.gnome.org/extension/6682/astra-monitor/), v19 seems to be the latest published version.

Yet, in Extension Manager 0.5.0, that build from extensions.gnome.org reports itself as version 30:
![image](https://github.com/AstraExt/astra-monitor/assets/4571159/eb73b6bc-8b91-4cf2-bbc3-fb20511a0dc8)
Did I overlook something here? Where does the version 30 come from? And is it deliberate, that v21 is not yet available at the Gnome Extensions site?

**Comment by ljuzig** [comment]
I agree that there is a bit of a mess in the way version numbers are handled on [extensions.gnome.org](extensions.gnome.org) (EGO) but I can't do anything about that. When I upload a build, they assign an internal version number. This number incrementally increases each build that is uploaded. Each time a build is uploaded it goes through a review process that checks the code and sometimes requires changes if any part of the code does not adhere to **EGO**'s rules. For each change, there is a new build upload and the version increases. I sent the **v20** version for review but it was not accepted in time so it was replaced by **v21** which is still awaiting review (the review process is quite slow), that is why there is still the v19 version in the store. The **30** you see is the internal version which in theory should not be exposed to users but is just part of the metadata, I think it is an **Extension Manager** error. I use **Extensions** and the version displayed is the right one.

This is also why in the extension's prefs you may see `21 (EGOv33)`:
![image](https://github.com/AstraExt/astra-monitor/assets/11982322/b4b99bab-6aaf-4668-93dc-3b0b2d3478dd)

**Comment by ljuzig** [comment]
About the **Extension Manager** version problem there is an issue on their github to include version-name:
[Confusion about version numbers #113](https://github.com/mjakeman/extension-manager/issues/515)
