### ISSUE TITLE
GPU stats not showing

### ISSUE THREAD

**Issue by psweet** [AstraExt/astra-monitor#116]
## Description

The GPU information is not shown at all, it shows -%.

## Steps to Reproduce

1. Installed amdgpu_top
2. Installed astra monitor
3. Enabled the gpu settings

## Screenshots

![image](https://github.com/AstraExt/astra-monitor/assets/49662397/2365e6a2-3bac-4461-913f-bd873e993d18)

![image](https://github.com/AstraExt/astra-monitor/assets/49662397/27354c52-807a-4fcd-b21d-c4b28d609783)

## Environment

- Astra Monitor Version 21 (EGOv34)
- GNOME 46
- Arch Linux
- AMD 7900XTX (Though the iGPU also doesn't work i9 12900k)

**Comment by Thorazin** [comment]
I have the exact same problem and was coming here to write about it.
![Screenshot from 2024-04-22 21-25-23](https://github.com/AstraExt/astra-monitor/assets/36058075/26c3be03-ef3b-4f13-9c6a-05617dc582ce)
![Screenshot from 2024-04-22 21-25-15](https://github.com/AstraExt/astra-monitor/assets/36058075/3792f7b2-443c-4eff-813d-37d9b00cc053)


Ryzen 9 7950X
Powercolor Red Devil 7900XTX
Gnome 46
Ubuntu 24.04
kernel 6.8.0.22 generic

amdgpu_top and Gtop installed

**Comment by ljuzig** [comment]
could you please run these command in your terminal and paste here the output?
`which amdgpu_top`
*and*
`amdgpu_top -J -u 5 -s 1000 -n 1`

**Comment by psweet** [comment]
Certainly!
`[psweet@SweetX9 ~]$ which amdgpu_top
/usr/bin/amdgpu_top
[psweet@SweetX9 ~]$ amdgpu_top -J -u 5 -s 1000 -n 1
{"amdgpu_top_version":{"major":0,"minor":8,"patch":2},"devices":[{"GRBM":{"Color Block":{"unit":"%","value":0},"Depth Block":{"unit":"%","value":0},"Geometry Engine":{"unit":"%","value":0},"Graphics Pipe":{"unit":"%","value":1},"Primitive Assembly":{"unit":"%","value":0},"Shader Export":{"unit":"%","value":0},"Shader Processor Interpolator":{"unit":"%","value":0},"Texture Pipe":{"unit":"%","value":0}},"GRBM2":{"Command Processor -  Compute":{"unit":"%","value":0},"Command Processor -  Fetcher":{"unit":"%","value":1},"Command Processor - Graphics":{"unit":"%","value":0},"Efficiency Arbiter":{"unit":"%","value":0},"Render Backend Memory Interface":{"unit":"%","value":0},"RunList Controller":{"unit":"%","value":0},"SDMA":{"unit":"%","value":0},"Unified Translation Cache Level-2":{"unit":"%","value":0}},"Info":{"ASIC Name":"GFX1100/Navi31","Chip Class":"GFX11","DeviceID":29772,"DeviceName":"AMD Radeon RX 7900 XTX","GL1 Cache per Shader Array":262144,"GPU Clock":{"max":2482,"min":500},"GPU Family":"GC 11.0.0","GPU Type":"dGPU","GTT Size":16706056192,"L1 Cache per CU":32768,"L2 Cache":6291456,"L3 Cache":100663296,"Memory Clock":{"max":1249,"min":96},"PCI":"0000:03:00.0","PCIe Link":{"max_dpm_link":{"gen":4,"width":16},"max_gpu_link":{"gen":4,"width":16},"max_system_link":{"gen":5,"width":16},"min_dpm_link":{"gen":4,"width":16}},"Power Cap":{"current":327,"max":350,"min":294},"Power Profiles":["BOOTUP_DEFAULT","3D_FULL_SCREEN","POWER_SAVING","VIDEO","VR","COMPUTE","CUSTOM","WINDOW_3D"],"RenderBackend":24,"ResizableBAR":false,"RevisionID":200,"Shader Array per Shader Engine":2,"Shader Engine":6,"Total Compute Unit":96,"Total ROP":192,"VBIOS":{"date":"2023/03/23 03:16","name":"XFX D702_XTX_A0_24GB_XFX_APM6206_79XTACFD","pn":"113-31XFSHBS1-L02","ver_str":"022.001.002.024.000001"},"VRAM Bit width":384,"VRAM Size":25753026560,"VRAM Type":"GDDR6","Video Caps":{"AV1":{"Decode":{"height":4352,"width":8192},"Encode":{"height":4352,"width":8192}},"HEVC":{"Decode":{"height":4352,"width":8192},"Encode":{"height":4352,"width":8192}},"JPEG":{"Decode":{"height":4096,"width":4096},"Encode":null},"MPEG2":{"Decode":null,"Encode":null},"MPEG4":{"Decode":null,"Encode":null},"MPEG4_AVC":{"Decode":{"height":4096,"width":4096},"Encode":{"height":2304,"width":4096}},"VC1":{"Decode":null,"Encode":null},"VP9":{"Decode":{"height":4352,"width":8192},"Encode":null}},"amdgpu_top_version":{"major":0,"minor":8,"patch":2},"drm_version":{"major":3,"minor":57,"patchlevel":0},"gfx_target_version":"gfx1100"},"Sensors":{"Average Power":{"unit":"W","value":83},"Edge Temperature":{"unit":"C","value":49},"Fan":{"unit":"RPM","value":488},"GFX Power":{"unit":"W","value":83},"GFX_MCLK":{"unit":"MHz","value":1249},"GFX_SCLK":{"unit":"MHz","value":46},"Input Power":null,"Junction Temperature":{"unit":"C","value":58},"Memory Temperature":{"unit":"C","value":64},"PCIe Link Speed":{"gen":4,"width":16},"VDDGFX":{"unit":"mV","value":704},"VDDNB":null},"VRAM":{"Total GTT":{"unit":"MiB","value":15932},"Total GTT Usage":{"unit":"MiB","value":117},"Total VRAM":{"unit":"MiB","value":24560},"Total VRAM Usage":{"unit":"MiB","value":1042}},"fdinfo":{"1228":{"name":"gnome-software","usage":{"CPU":{"unit":"%","value":0},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":2},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":10}}},"1531":{"name":"xdg-desktop-por","usage":{"CPU":{"unit":"%","value":0},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":2},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":10}}},"1619":{"name":"amdgpu_top","usage":{"CPU":{"unit":"%","value":0},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":0},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":0}}},"2297":{"name":"gnome-calendar","usage":{"CPU":{"unit":"%","value":0},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":2},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":10}}},"2300":{"name":"gnome-control-c","usage":{"CPU":{"unit":"%","value":0},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":0},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":0}}},"2541":{"name":"firefox","usage":{"CPU":{"unit":"%","value":0},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":24},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":203}}},"3086":{"name":"kgx","usage":{"CPU":{"unit":"%","value":0},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":12},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":43}}},"3148":{"name":"amdgpu_top","usage":{"CPU":{"unit":"%","value":1},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":0},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":0}}},"814":{"name":"Xorg","usage":{"CPU":{"unit":"%","value":0},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":28},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":223}}},"941":{"name":"gnome-shell","usage":{"CPU":{"unit":"%","value":0},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":16},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":496}}},"988":{"name":"mutter-x11-fram","usage":{"CPU":{"unit":"%","value":0},"Compute":{"unit":"%","value":0},"DMA":{"unit":"%","value":0},"Decode":null,"Encode":null,"GFX":{"unit":"%","value":0},"GTT":{"unit":"MiB","value":2},"Media":{"unit":"%","value":0},"VCN_JPEG":{"unit":"%","value":0},"VPE":null,"VRAM":{"unit":"MiB","value":10}}}},"gpu_activity":{"GFX":{"unit":"%","value":0},"MediaEngine":{"unit":"%","value":32},"Memory":{"unit":"%","value":0}},"gpu_metrics":{"Throttle Status":["TEMP_HOTSPOT"],"average_core_power":null,"average_cpu_current":null,"average_cpu_power":null,"average_cpu_voltage":null,"average_dclk1_frequency":512,"average_dclk_frequency":512,"average_fclk_frequency":null,"average_gfx_current":null,"average_gfx_power":null,"average_gfx_voltage":null,"average_gfxclk_frequency":10,"average_soc_current":null,"average_soc_power":null,"average_soc_voltage":null,"average_socclk_frequency":null,"average_socket_power":85,"average_temperature_core":null,"average_temperature_l3":null,"average_uclk_frequency":2487,"average_vclk1_frequency":812,"average_vclk_frequency":812,"current_coreclk":null,"current_dclk":512,"current_dclk1":512,"current_fclk":null,"current_gfxclk":10,"current_l3clk":null,"current_socclk":1500,"current_uclk":1249,"current_vclk":812,"current_vclk1":812,"fan_pwm":null,"header":{"content_revision":3,"format_revision":1,"structure_size":120},"pcie_link_speed":160,"pcie_link_width":16,"system_clock_counter":236456373316,"temperature_core":null,"temperature_edge":49,"temperature_gfx":null,"temperature_hotspot":58,"temperature_l3":null,"temperature_mem":64,"temperature_soc":null,"temperature_vrgfx":53,"temperature_vrmem":54,"temperature_vrsoc":54,"voltage_gfx":701,"voltage_mem":804,"voltage_soc":1040}}],"devices_len":1,"period":{"duration":1019,"unit":"ms"},"title":"amdgpu_top v0.8.2"}`

**Comment by ljuzig** [comment]
I think it's fixed but I can't be sure without testing on the actual hardware, if you can, please try this build and share a feedback:
`gnome-extensions install --force monitor@astraext.github.io.shell-extension.zip`
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/15077841/monitor%40astraext.github.io.shell-extension.zip)

**Comment by psweet** [comment]
All working now! Thanks!
