### ISSUE TITLE
Clicking the Settings icon on a specific tab should go directly to the relevent tab in extension's Settings.

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#12]
Thanks for creating such a useful GNOME extension! 

One simple enhancement (I am not sure if it is possible to implement though):

When I click the "Settings icon" on, say, the **Network** popup of the extension, the **General** tab of the "Settings window" is opened. Instead, directly the **Network** tab can be displayed.

**Comment by ljuzig** [comment]
I'm not sure about this one, I will investigate more after the next release. Thank you for the suggestion, if doable it would be very  useful with no doubt.
