### ISSUE TITLE
"Main Disk" label in storage preferences has not enough space if name of disk is long (e.g. LUKS)

### ISSUE THREAD

**Issue by jtl5770** [AstraExt/astra-monitor#126]
## Description

Having a luks crypted SSD, the main disk in storage preferences has a very long name leading to a distorted label

![image](https://github.com/AstraExt/astra-monitor/assets/24967370/645758ab-1fba-422e-9742-aae3e3bd08b0)
## Environment

-   **Astra Monitor Version**: 25 EGOv42
-   **GNOME Version**: 46
-   **Operating System and Version**: Fedora 40

**Comment by lepa22** [comment]
This must be the same as #80, but for for the _Storage_ menu instead of the _Sensors_ menu. The fix should be similar I guess and I think that it should be implemented for all menus having dropdowns to avoid such issues in the future.
