### ISSUE TITLE
Memory meter overflowing/overlaping topbar

### ISSUE THREAD

**Issue by paulo-evangelista** [AstraExt/astra-monitor#127]
Memory meter overlaps the topbar, sometimes even taking the entire height of the screen. Happens when switching workspaces and disappears in ~5secs

![image](https://github.com/AstraExt/astra-monitor/assets/99093520/bb0556e1-2595-485e-b2ca-3265c6a6f3c7)

-    **Astra Monitor Version**: 25
-   **GNOME Version**: 46
-   **Operating System and Version**: Fedora 40
-   **Other Relevant System Information**: RTX 3060, Non-free drivers on X11

**Comment by RuofengX** [comment]
Same issue. The "disappear time" is exact the update/refresh time.

- Astra Monitor Version: 25
- GNOME Version: 46
- Operating System and Version: Fedora 40
- Other Relevant System Information: Minisforum V3 tablet.

**Comment by ljuzig** [comment]
I've been able to reproduce this, I'm gonna fix it soon! Thank you!

**Comment by Raindrac** [comment]
In case it helps identify the cause, I've observed that the amount of overflow is strongly correlated with the amount of time that I spend in fullscreen, eventually reaching the bottom of my display if I spend over an hour in fullscreen.

**Comment by eboye** [comment]
I've been looking into this and I think I know how it can be fixed.

I think in repaint function the height is huge after going from full screen so it needs to be capped like this:
```js
const maxHeight = height > 64 ? 64 : 0;
```
and then use the maxHeight instead of height provided by the system. Maybe I'm wrong, but still worth to try. 64 is arbitrary number I came up with.

**Comment by ljuzig** [comment]
@eboye This bug needs a proper fix. If the user has dash-to-panel with 100px height, capping to 64 will cut the bars. Gnome is very customizable and I cannot set an arbitrary value. I will work on this next, cuz it's a very bothering bug.

**Comment by eboye** [comment]
I know, I just pointed to where the problem might be lying

**Comment by ljuzig** [comment]
I found a temporary solution to this. Gonna come back taking a deeper look at this at a later time, but the resize of the bars are now disabled whenever an app goes fullscreen on the very same monitor.
