### ISSUE TITLE
Icon the launch the GNOME System Monitor is missing

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#128]
## Description

I noticed that the icon to launch the GNOME System Monitor is missing from the menus. I am not exactly sure when this disappeared, but I have several Ubuntu 24.04 systems and all are missing this icon.

## Steps to Reproduce

1. On Ubuntu 24.04 install latest version of Astra Monitor;
2. Click on any item (like CPU, Memory, etc) to show its menu;
3. On previous versions, besides the *Settings* icon there was an icon that will launch the *GNOME System Monitor*.

## Screenshots

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/18f20e51-d639-4863-9b02-a95d632a6ea4)

## Environment

-   **Astra Monitor Version**: 25 (EGOv42)
-   **GNOME Version**: 46
-   **Operating System and Version**: Ubuntu 24.04 LTS
-   **Other Relevant System Information**:

**Comment by Malix-off** [comment]
Same on Fedora 40 Gnome 46

**Comment by lepa22** [comment]
Icon is still there with 25 (EGOv42) on Fedora 39.
