### ISSUE TITLE
"Memory Used" is inconsistent depending on the "Data Source"

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#129]
## Description

The amount of *Used Memory* reported changes drastically when the "Data Source" is changed from **GTop** to **/proc/meminfo**.

## Steps to Reproduce

1. On Ubuntu 24.04 install the latest version of Astra Monitor;
2. Select **auto** (or **GTop**) in **Settings → Memory → General → Data Sources** and look at the amount of **Used** Memory reported.
3. Now  change this setting to **/proc/meminfo** and look again: The amount reported is quite different.
4. The amount reported in step 3 is consistent with *GNOME System Monitor*, whereas the one in step 2 is well below the actual value.

## Screenshots

GTop: 
![image](https://github.com/AstraExt/astra-monitor/assets/113997707/ba73f4b9-1099-49a8-b285-a438b1a5f2cf)
/proc/meminfo:
![image](https://github.com/AstraExt/astra-monitor/assets/113997707/54686832-a49e-4fb5-a5d5-6c0c415ad6bf)

## Environment

-   **Astra Monitor Version**: 25 (EGOv42)
-   **GNOME Version**: 46
-   **Operating System and Version**: Ubuntu 24.04 LTS
-   **Other Relevant System Information**: 

## Additional Context

Note: In my **Settings** configuration,  **Used Memory** is calculated as **Used = Total - Available**.

**Comment by ljuzig** [comment]
GTop takes into consideration Slab memory ([see source code](https://gitlab.gnome.org/GNOME/libgtop/-/blob/master/sysdeps/linux/mem.c?ref_type=heads#L61)), while the default System Monitor formula does not. This makes GTop's calculation more comprehensive and accurate. However, it does result in a discrepancy when comparing to System Monitor. 

I'm considering whether to include Slab memory in the `/proc/meminfo` source as well to match GTop's calculation. For now, I might leave it as is to provide results that are more aligned with what System Monitor displays, if anyone want it that way.

**Comment by fedkad** [comment]
A special option in **Memory** -> **Data Sources** may be added, e.g., "_Compatibility with System Monitor_"
