### ISSUE TITLE
Data measurement unit customization: kB/s | kBps |  kBs | KiB/s | KiBps | KiBs

### ISSUE THREAD

**Issue by ljuzig** [AstraExt/astra-monitor#13]
## Description
Add an option to choose the preferred unit to display data measurements.
ie:
kB/s, kBps, kBs
KiB/s, KiBps, KiBs

**Comment by fedkad** [comment]
+1
Also _kBps_ vs. _kbps_ (kilo bytes per second vs. kilo bits per second) for **Network**.

**Comment by ljuzig** [comment]
I think this covers all flavors...
![Screenshot from 2024-01-13 17-39-21](https://github.com/AstraExt/astra-monitor/assets/11982322/a8b2aa97-cd8e-4421-b95f-27be38c334e5)

**Comment by fedkad** [comment]
> I think this covers all flavors... ![Screenshot from 2024-01-13 17-39-21](https://private-user-

Yes, but "../s" and "..ps" are virtually equal, so they should be in the same selection. The last two entries are not necessary. In short, only (the first) four entries are needed.

**Comment by ljuzig** [comment]
That's intentional. I want to give the user more choices on how to visualize the data as they prefer. Last two options are just non-standard options for very compact output.
