### ISSUE TITLE
Network tab performance issue

### ISSUE THREAD

**Issue by AlexeyMatskevich** [AstraExt/astra-monitor#130]
First of all, thank you very much for the work you've done.

## Description

The rendering of the network tab is very slow and causes the system to freeze, while the rendering of the other tabs works well or perfectly.

## Steps to Reproduce

[Screencast from 2024-06-05 18-54-46.webm](https://github.com/AstraExt/astra-monitor/assets/45947106/87e7a237-6723-4ac7-9364-c6482b82f7cd)

## Environment

-   **Astra Monitor Version**: Version 21
-   **GNOME Version**: 46 on Wayland
-   **Operating System and Version**: NixOS 24.05 (Uakari)
-   **Other Relevant System Information**: AMD Ryzen™ 9 5950X, NVIDIA GeForce RTX™ 4090 555 driver , 128.0 GiB

## Additional Context

I realize that ideally I should be testing this on a more recent version such as 24, however it seems the NiX Store doesn't have a newer version, feel free to close this because of the older version.

**Comment by AlexeyMatskevich** [comment]
After install [wirelesstools](https://hewlettpackard.github.io/wireless-tools/Tools.html) and [pciutils](https://mj.ucw.cz/sw/pciutils/) the performance problems are gone.

**Comment by iongion** [comment]
I am on Ubuntu 26.04, hovering over the network or the storage, mouse pointer becomes very sluggish, anyone else ? Sorry for necroposting, is like above!
