### ISSUE TITLE
Gtop not recognized

### ISSUE THREAD

**Issue by kmand** [AstraExt/astra-monitor#132]
Welcome tells me that gtop is not installed. I'm on ubuntu 24.04. Gtop is only available via npm, and I  did do an install with npm. Gtop runs properly. It was not a dpkg install.  Any way to fix this?

**Comment by ljuzig** [comment]
Libgtop is available on Ubuntu 24.04, you can install it with:
`sudo apt install gir1.2-gtop-2.0`
The npm version won't work.
