### ISSUE TITLE
Huge RAM usage by nvidia_smi 

### ISSUE THREAD

**Issue by giosal** [AstraExt/astra-monitor#134]
It's my understanding that AstraMonitor uses nvidia-smi to display NVIDIA GPU stats, doesn't it?

So, on the daily build of Ubuntu 24.10 with NVIDIA 555 drivers, nvidia-smi is using all available RAM, around 25 GB.

Please let me know which logs should I send to you.
![image](https://github.com/user-attachments/assets/998dd34a-dceb-4185-b3ce-909f6e74d062)

**Update**
As soon as I killed AstraMonitor, the RAM usage decreased as it also killed nvidia-smi process, and I'm now at 23 GB free
![image](https://github.com/user-attachments/assets/b5b6e6ad-52e3-4c8b-988e-ab86bb79460f)

**Comment by ljuzig** [comment]
This must be a `nvidia-smi` bug. Are you still experiencing this issue?

**Comment by giosal** [comment]
Yes, still experiencing this issue. It definitely seems to be nvidia-smi bug., I've tested nvidia-smi directly without AstraMonitor. So, please accept my apologies, I'll report this to NVIDIA
