### ISSUE TITLE
Has development of Astra Monitor ceased?

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#135]
## Description

It seems that the development of **Astra Monitor** addon has stalled. I hope the developer of this software is doing well and nothing bad has happened.

## Steps to Reproduce

1. Please, open https://github.com/AstraExt/astra-monitor/blob/main/README.md 
2. Look at **Roadmap** section.
3. Nothing new since May 2024.

## Screenshots

Project seems to have stalled before the **Release Phase**:

![image](https://github.com/user-attachments/assets/71ecc094-5c88-40b1-81f1-6de50ab33259)

## Environment

-   **Astra Monitor Version**: 25 (EGOv42)
-   **GNOME Version**: 46
-   **Operating System and Version**: Ubuntu 24.04
-   **Other Relevant System Information**:

**Comment by ljuzig** [comment]
Hello, I had to prioritize other things and temporarily suspend the development of Astra Monitor. Development will very likely resume after the summer at a more relaxed pace than before. I will update the roadmap soon.
