### ISSUE TITLE
Disk usage / disk free space header labels should be next to the disk icon (before activity graph and label)

### ISSUE THREAD

**Issue by nekohayo** [AstraExt/astra-monitor#139]
## Description

The disk free header label ("10.7 GB" in the screenshot below) is placed in what feels like confusing place, because it afterthe disk IO activity graph and labels, which can be blank when not meeting the activity threshold, and it creates a big empty space that is distant  from the disk itself. This also becomes apparent when you use the disk icon coloring warning feature on full disk.

I believe it would clearer if:
* The disk usage + free labels were placed right next to the disk icon
* When both (or multiple) labels are activated (i.e. both disk usage vs disk free), put a descriptive label next to the unit (ex: "10.7 GB free"). I have plenty of space available for that on my widescreen :)

## Screenshots

![image](https://github.com/user-attachments/assets/dd4ac6f7-ea5f-48f4-b17c-517cc6625b72)

## Environment

-   **Astra Monitor Version**: 25 (EGOv42)
-   **GNOME Version**: GNOME 46
-   **Operating System and Version**: Fedora 40

**Comment by nekohayo** [comment]
I also see now that those things are reorderable, but I think the default order would benefit from having the IO activity ones at the end by default (as they can be variable width), and still, the "used" vs "free" descriptive labels (when more than one textual value is shown) would be beneficial :)

![image](https://github.com/user-attachments/assets/cd7ab616-d52c-42c3-9cbc-07f049d2ecbf)

**Comment by ljuzig** [comment]
Thank you for your suggestion, the default is already the same as you mentioned, but you probably installed the extension in a very old version, so it saved in your data the old sorting. New user will have this order:
`storage: ['icon', 'bar', 'percentage', 'value', 'free', 'IO bar', 'IO graph', 'IO speed']`
