### ISSUE TITLE
Enhancement: Optionally, show disk IO activity in "Storage Usage Bar"

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#14]
First of all, please forgive me if I misunderstood some of the options that I mention below:

Currently, the **Storage Usage Bar** shows how full a disk is.

Although this may be useful for many users, for people like me who have a relatively stable system where storage usage (=fullness) does not change rapidly by time, the current amount of disk IO (disk reads and disk writes per second) is more important.

I know that **IO History Graph** and **IO Speed** can be used more or less for this purpose, but I would like to see the instant IO activity (MB read & write per second) just like the current network IO rate is shown in **Network Usage Bar**.

Another point which is not clear about **Storage** setting tab is the **Main Disk** option. I guess this indicates which disk will be "monitored" in the "**Header**". I have tested and seen that the "Main Disk" option is used for **Storage Usage Bar**, but _not_ for **IO History**. An option to merge all the disks in the system, so that the **Storage Usage Bar** in the "Header" will show the _total storage usage_ may also be useful.

**Comment by ljuzig** [comment]
A Store IO Activity Bar is doable and a nice addition, it is now on the list. As for your other request I'm not sure I'm getting what you do mean.
Currently all the graphs/data in the header are globals. Main Disk is used ONLY for the Disk Space Usage bar and to properly order the list in the dropdown menu. "Storage Usage Bar" should be renamed in "Main Disk Space Bar" or something like that to make it more clear.

**Comment by fedkad** [comment]
I say "_the "Main Disk" option is used for **Storage Usage Bar**_", you say "_Main Disk is used ONLY for the **Disk Space Usage** bar and to properly order the list in the dropdown menu._", so we are saying the same thing I guess! 
:)
