### ISSUE TITLE
Convert `(R)` registered marks in CPU/GPU names to ® unicode symbols

### ISSUE THREAD

**Issue by nekohayo** [AstraExt/astra-monitor#140]
## Description

This is a small UX suggestion to make CPU and GPU names nicer throughout the user interface: automatically detect `(R)` (and probably `(TM)` and `(C)`) in the product and vendor names, and replace that with nicer unicode symbols:  ®, ™, and ©, like GNOME Settings' Details pane does.

It would take less space and be more visually pleasing.

## Screenshots

![image](https://github.com/user-attachments/assets/f13c50fd-a5dd-40a0-a854-954a65331388)

## Environment

-   **Astra Monitor Version**: 25 (EGOv42)
-   **GNOME Version**: GNOME 46
-   **Operating System and Version**: Fedora 40

**Comment by ljuzig** [comment]
CPU name wasn't shortened in the menu like GPUs, so this is a great suggestion. Thank you!

**Comment by fedkad** [comment]
I don't think this "shortening" works in my case (v.26 - EGOv43):

![image](https://github.com/user-attachments/assets/68505800-c2ae-4769-9003-5fad0907438f)
