### ISSUE TITLE
gnome 47 support

### ISSUE THREAD

**Issue by thenameisluk** [AstraExt/astra-monitor#143]
GNOME 47.rc has been released, with the stable release set for September 18.

it would be nice to get it working there or just update [manifest](https://github.com/AstraExt/astra-monitor/blob/main/metadata.json) if it already works

**Comment by thenameisluk** [comment]
it seams to be actually working so manifest update should be enough

**Comment by ljuzig** [comment]
Nothing really relevant to the extension changed so adding 47 to metadata as suggested is enough. I could add support to accent color, but right now I'm not sure where there might be a real use for it. I don't want to use it for the default chart colors, cause we have two colors and it would introduce the problem of the second color, so for now I'll postpone it to a later version.
Going to issue a new release soon anyway, thank you!
