### ISSUE TITLE
I don't think this "shortening" works in my case (v.26 - EGOv43):

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#144]
I don't think this "shortening" works in my case (v.26 - EGOv43):

![image](https://github.com/user-attachments/assets/68505800-c2ae-4769-9003-5fad0907438f)

_Originally posted by @fedkad in https://github.com/AstraExt/astra-monitor/issues/140#issuecomment-2354916751_

**Comment by ljuzig** [comment]
The shortening is only active in the menu, not in the info popup. That's by design. The detailed information must reflect `lscpu` output.
