### ISSUE TITLE
Make Sensor source popup wider

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#15]
## Description
The popup that allows you to select a source for *Sensors* is not wide enough, so the text gets truncated, making the selection of a source difficult. The pop up should be made wider, and adaptable to the contents up to a maximum width. In cases where a source is longer than the set maximum width (not sure if a source can be that long), it would be nice if a tooltip were shown with the full name of the source.

The same happens to the (newly created) *Used Memory* selection type, but I'm not opening a new issue for this, since the fix should be the same and to avoid cluttering the issues section.

## Steps to Reproduce
1. Install and enable the extension.
2. Go to *Sensors* tab.
3. Click the *Sensor 1/2 Source* value.
4. The dropdown shows the available sources, but they are truncated, so not easy to select.

## Screenshots
![image](https://github.com/AstraExt/astra-monitor/assets/16370046/5a7c929a-b46c-4954-ab65-e88544f1f68d)

## Environment
- **Astra Monitor Version**: v3 (not yet released)
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39

**Comment by ljuzig** [comment]
Fixed:
![Screenshot from 2024-01-14 02-17-46](https://github.com/AstraExt/astra-monitor/assets/11982322/305074ee-f0c4-4049-abac-9798a3629aed)
