### ISSUE TITLE
Network stats causes stuttering

### ISSUE THREAD

**Issue by pocoraven** [AstraExt/astra-monitor#156]
## Description

When hovered on the Network stats, the display stutters about every half a second. This does not occur with any of the other stats.

## Steps to Reproduce

Simply hover over the Network stat. (if enabled)

## Screenshots

https://github.com/user-attachments/assets/6b862812-2fc8-4be9-ab41-a4efa06253ca

## Environment

-   **Astra Monitor Version**: 29 (EGOv46)
-   **GNOME Version**: 47
-   **Operating System and Version**: endeavorOS Neo
-   **Other Relevant System Information**: Intel iGPU

## Additional Context

This could be due to the integrated Intel GPU on my laptop, but I've never had this issue before, I'm curious if AMD/NVIDIA users are facing the same problem as well.

**Comment by fedkad** [comment]
I am using NVIDIA and just tested: I have no such problem. However, there may be many other factors causing this problem.

**Comment by pocoraven** [comment]
A restart resolved this issue.

**Comment by pocoraven** [comment]
A restart seems to have resolved this issue.
