### ISSUE TITLE
Enhancements for future versions

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#16]
I am testing your version 3.

I have some proposals for enhancements, in case you may want to consider implementing:

* **CPU Menu / System Uptime** section. A popup window showing _load average_ like the `uptime` command (or `top` command's first line) may be useful.
* **Memory Menu**. The breakdown in graph is not clear: The blue part is (probably) the **Used** part; the red part is **Cached** or what? You may want to make this configurable (besides the _Breakdown_ toggle).
* **Memory Header**. The **Show Percentage** toggle is useful. An addition like **Show Usage** (in GBs for example) may be more useful to me.
* **Storage** tab. Disk names (like sda, sdb1, etc.) are OK. But, where are these disks currently mounted? A popup may show this, plus any information (fs type, usage, total size in GBs, etc.) like the `df -T` command.
* **Network** tab. Cumulative upload/download data is missing. A pop menu for each network interface may give more information like the `ifconfig` command.
* **Sensors** tab. In my case, _the icon_ and _the unit (**A**) is missing_ for **BAT0-acpi-00** / **Curr1** Input sensor.

**Comment by ljuzig** [comment]
Very interesting suggestions. Some of them are already in my TODO list.
I took note of everything missing.
About the missing icon in sensors, would you mind sharing your _sensors_ terminal output?

**Comment by fedkad** [comment]
The missing icon is shown with a red arrow below:
![image](https://github.com/AstraExt/astra-monitor/assets/113997707/cfaaa94f-4692-4f67-b5e5-8a94b93017c0)

The output from the `sensors` command is:
```
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:            N/A  

BAT0-acpi-0
Adapter: ACPI interface
in0:          12.99 V  
curr1:       394.00 mA 

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +51.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +45.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +51.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +48.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +47.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +49.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +50.0°C  (high = +100.0°C, crit = +100.0°C)

pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:        +58.0°C  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +48.0°C  (crit = +100.0°C)
temp2:        +48.0°C  (crit = +100.0°C)
```

**Comment by ljuzig** [comment]
@fedkad The missing _Icon_ and _Unit_ should be fixed in the just released version, test it out! I'm not closing this to keep track of the other requests.

**Comment by fedkad** [comment]
> @fedkad The missing _Icon_ and _Unit_ should be fixed in the just released version, test it out! I'm not closing this to keep track of the other requests.

Yes. It is OK in v4:

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/d4608794-22f5-4a50-b3d6-c1a9831b08a7)

**Comment by ljuzig** [comment]
Load average added in commit [b7fbb45](https://github.com/AstraExt/astra-monitor/commit/b7fbb45fcf017619962d2b2e1d1337cb1ed9aab4)

**Comment by ljuzig** [comment]
I think everything asked in this issue will be available in the next version I'm gonna release soon. If something particular is missing please create a new issue!

**Comment by fedkad** [comment]
I think my **Storage** and **Network** suggestions are not addressed (yet).

But, it is OK; I can create a new issue in the future.

**Comment by ljuzig** [comment]
they should be addressed in the version about to be released, please wait extensions.gnome.org to review and approve it
