### ISSUE TITLE
NVIDIA controller is not displayed in the GPU list

### ISSUE THREAD

**Issue by MiceX** [AstraExt/astra-monitor#162]
## Description

NVIDIA controller is not displayed in the GPU if it's named as "3D controller" in `lspci` output:
```
01:00.0 3D controller [0302]: NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile] [10de:1c8c] (rev a1)
	Subsystem: Dell GP107M [GeForce GTX 1050 Ti Mobile] [1028:087c]
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
```

## Environment

-   **Astra Monitor Version**: 46
-   **GNOME Version**: 46
-   **Operating System and Version**: Ubuntu 24.04.01 (kernel Linux 6.8.0-49-generic)
-   **Other Relevant System Information**: Dell XPS 15 (9570), GPUs: Intel® UHD Graphics 630 (CFL GT2) and NVIDIA GeForce GTX 1050 Ti with Max-Q Design

## How to fix

To resolve this issue add this '3d controller' here https://github.com/AstraExt/astra-monitor/blob/954abe1581c2a51c390a983cfd6aaa45a677baaa/src/utils/utils.ts#L1286

**Comment by ljuzig** [comment]
Thank you, it will be fixed in the next release!
