### ISSUE TITLE
Processor info very big and look messy

### ISSUE THREAD

**Issue by Anifyuli** [AstraExt/astra-monitor#18]
## Description

Processor info hover action is very big and look messy and not uniform too with other info

## Steps to Reproduce

1. Show processor info
2. Hover to processor name
3. It look messy

## Screenshots

![image](https://github.com/AstraExt/astra-monitor/assets/73734843/6e10ffc5-ad6d-4f3e-a2ba-c7edc3abe0ce)

## Environment

- **Astra Monitor Version**: 4 (EGOv6)
- **GNOME Version**: 45.2
- **Operating System and Version**: Ubuntu 23.10
- **Other Relevant System Information**: Intel core-i5 8350U, Intel UHD 620

## Logs

N/A

## Additional Context

N/A

**Comment by ljuzig** [comment]
What's your screen resolution? I have to well figure out how to solve the problem of a screen too low to hold all the information. Today I ran some tests for a scrolling container but I don't really like the mouse interaction since it's a popup that disappears when the mouse goes outside the name. A solution might be to selectively remove some lines until the list of information completely fits on the screen.

**Comment by fedkad** [comment]
> A solution might be to selectively remove some lines until the list of information completely fits on the screen.

I suggest you split the information into two: **Basic** and **Extended** and optionally allow the user to disable the **Extended** info.

**Comment by fedkad** [comment]
Then, a cascading menu is the second option coming to mind. But, this will make the screen layout and usage more complex.

**Comment by ljuzig** [comment]
@Anifyuli  This should be fixed in the next release. When the screen is short multi-lines are stripped to a single line. If it's still not ok comment here or open a new ticket.

**Comment by Anifyuli** [comment]
> What's your screen resolution? I have to well figure out how to solve the problem of a screen too low to hold all the information. Today I ran some tests for a scrolling container but I don't really like the mouse interaction since it's a popup that disappears when the mouse goes outside the name. A solution might be to selectively remove some lines until the list of information completely fits on the screen.

I use 768P screen resolution
