### ISSUE TITLE
[Feature request] Deal with gazillion docker network interfaces!

### ISSUE THREAD

**Issue by aurelijusrozenas** [AstraExt/astra-monitor#20]
First of all - wow, I love it! ✨  

Now, I am most likely an edge case, but using docker makes network status not very usable.
Not sure how it can be handled though.
- Maybe sort somehow? If it is possible it understand which interfaces are "real", they could be at the top.
- Maybe introduce some kind of filtering? Checkboxes for interfaces in settings? Exclusion rule?

Below is my list / screenshot. As you can see, really not standard stuff :D
- Wifi at the top and lan at the bottom, which is what I want.
- Wireguard VPN, custom name `apamoka`.
- ZeroTier VPN, prefixed with `zt`.
- And then the promised gazillion docker interfaces 🤯 `veth` and `br-` prefixes in my case.

![image](https://github.com/AstraExt/astra-monitor/assets/3273544/1a255813-a7ec-49de-8c34-5d4ac53b9142)

**Comment by ljuzig** [comment]
Thank you! I don't think you are an edge case, having a lot of virtual networks for docker/podman/kvm or what-else, is something that can very well be expected on Linux. I don't want to ignore a network based on its _type_, a virtual network might be the main network for someone. I think we need a filter to selectively exclude some network on request.

**Comment by ljuzig** [comment]
In the next release you will be able to selectively hide Network interfaces.
![Screenshot from 2024-01-16 01-18-15](https://github.com/AstraExt/astra-monitor/assets/11982322/cb785a15-de97-4a13-be3d-6d22217d42a1)
