### ISSUE TITLE
About tab, part of content, and close button get hidden after a window width

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#21]
## Description
The *About* tab, part of the window contents, and the close button get hidden if the window is smaller than a specific width. All these should be visible at all times, so the minimum width of the settings window should be set so that nothing gets hidden.

## Steps to Reproduce
1. Install and enable the extension.
2. Open the extension's settings.
3. Make the width of the extension's settings window as small as possible.
4. The *About* tab, part of the window contents, and the close button get hidden. 

## Screenshots
Normal window:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/e91f41d2-c339-4022-b821-4f224f1559fe)

Window with width below a certain threshold:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/33a61b1c-bffd-423c-af0a-722df2196c4c)

## Environment
- **Astra Monitor Version**: 4
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

## Additional Context
Perhaps the minimum height of the settings window should similarly be set to a somewhat larger value.

**Comment by ljuzig** [comment]
I've set proper minimum sizes, ty!
