### ISSUE TITLE
Clicking on the extension's settings from the CPU top bar menu takes you to General tab

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#23]
## Description
Clicking on the extension's settings from the CPU top bar menu takes you to the _General_ tab instead of the _Processors_ tab.
 
## Steps to Reproduce
1. Install and enable the extension.
2. Click on the CPU item in the top bar.
3. Click on the settings icon in the CPU dropdown.
4. The extension's Preferences window opens in the _General_ tab instead of the _Processors_ tab.

## Environment
- **Astra Monitor Version**: 5
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

**Comment by ljuzig** [comment]
Oops, typo! Fixed, thank you!
