### ISSUE TITLE
Menu title different in top bar dropdown and extension's Preferences window for CPU item

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#24]
## Description
The menu title in the top bar dropdown is different than in the tab of the extension's Preferences window for the CPU item. The top bar dropdown shows the name *CPU* while the tab in the Preferences window is labeled as *Processors*. All other items have the same titles both in the dropdown and in the Preferences tab, so this should be the case for the *CPU* item as well. My suggestion is to rename the title of the dropdown to *Processors*.

## Steps to Reproduce
1. Install and enable the extension.
2. Click the CPU item in the top bar. It is titled as _CPU_.
3. Open the extension's settings. The tab for the CPU settings is labeled as *Processors*.

## Screenshots
Title of CPU dropdown:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/a98e62bd-901b-4512-ad94-4daa0eca2fc4)

Label of CPU tab in extension's settings:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/f05eba6a-706e-434e-b5fb-69a5c51761e9)

## Environment
- **Astra Monitor Version**: 5
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

**Comment by ljuzig** [comment]
That's actually on purpose. The menu is for all processors (ie: CPU and GPU) and the top part is for CPUs and the bottom part is for GPUs (for now just listing them). The top part is labeled as CPU cuz it's a single socket, after multiple sockets detection will be implemented it should dynamically change CPU to CPUs like it's doing for GPU => GPUs.

I will add GPU stats in a later version including graph, top processes, etc...
I chose to aggregate CPU and GPU in a single processors menu (like iStats Menus do) cuz I actually don't think that anybody would be interested to have a separate option for that, but I think I will add options to place GPU graph/bar/percentage on the GNOME Top Bar anyway.

Anyway, back to the OP, when I'll work on GPU stats I will eventually split settings inside "Processors" to CPU and GPU to make that more clear.

**Comment by lepa22** [comment]
OK, thanks for clarifying! And I was actually wondering about the purpose of the GPU option in the settings, since selecting a GPU doesn't actually provide any additional info. With your planned feature the option makes absolute sense.

**Comment by ljuzig** [comment]
@lepa22 I noticed that on GPUs list you do have two identical very generic entries.
Can you run `lspci -nnk | grep -i vga -A3` in the terminal and share the result here?

**Comment by lepa22** [comment]
Of course! Here it is:
```
$ lspci -nnk | grep -i vga -A3
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07)
	Subsystem: Hewlett-Packard Company Device [103c:84f7]
	Kernel driver in use: i915
	Kernel modules: i915
--
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] [10de:1c8d] (rev a1)
	Subsystem: Hewlett-Packard Company Device [103c:84f7]
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia
```

**Comment by ljuzig** [comment]
Interesting, I'm gonna try to improve that.

**Comment by lepa22** [comment]
Good! Feel free to ping me for anything you might need!

**Comment by ljuzig** [comment]
If you got a chance, try manually installing this version replacing the current one and see if it has improved video card detecting:
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/13962813/monitor%40astraext.github.io.shell-extension.zip)

**Comment by lepa22** [comment]
Not really improved. Both cards are shown as *HP*:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/a0b80b53-4476-4564-a4b1-d25fd44fcbf5)

I guess the cards should be shown as the *Name* parameter in the hover window. The Intel card should be shown as *Intel Corporation UHD Graphics 620*:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/a993763b-8bb8-4f19-a4ac-40bfb582830b)

The NVIDIA card should be shown as *NVIDIA Corporation GP107M*:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/6c359df5-0526-4da3-b006-fef5df06d4e8)

(Maybe without "Corporation" to keep the name shorter)

**Comment by ljuzig** [comment]
@lepa22 Ok sorry I made a very silly mistake. This one should work! If it does, I will add it to the upcoming release:
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/13982562/monitor%40astraext.github.io.shell-extension.zip)

**Comment by lepa22** [comment]
Excellent! Card names are displayed properly!

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/f9a4bc22-f391-4b0a-a67b-a45a8fe8647a)

Thank you for your work! :1st_place_medal:
