### ISSUE TITLE
Enhancement: Minimal popup info on mouse hover

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#25]
It would be nice to have a very minimal (one or two values) popup info for each section, when mouse pointer is moved over the relevant section's "header".

For example:
* the total _CPU / GPU usage percentage_ for the **Processors** header,
* the _usage percentage and/or GB used_ for the **Memory** header,
and so on.

**Comment by ljuzig** [comment]
That's a very cool suggestion, will surely do! Obviously it will be enable by default but with an option to disable it.
It's on the TODO list but I can't say if it'll fit the next release.

**Comment by ljuzig** [comment]
New release adds minimal non-customizable Tooltip (you need to enable it). I will add more features in the future.
![Screenshot from 2024-01-19 02-14-14](https://github.com/AstraExt/astra-monitor/assets/11982322/fcf63a86-0cf8-4a14-a576-220c234f6e17)

**Comment by fedkad** [comment]
Thanks for the v6 update. But, tooltips are unreadable for me, probably due to large fonts:

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/4423e0bf-23af-457d-bcc1-7d6192ab9a9f)

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/738e7c2f-b032-4ac5-95d0-252b7d6eec13)

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/8a9552ca-18fc-462a-ad6e-8be3c005bd15)

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/548eecec-0d06-46c3-b196-1d3790facc64)

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/d69a5b8f-cbde-4103-b4c8-e48f5d30709b)

So, they are useless so far! :(

**Comment by ljuzig** [comment]
Noticed that, please follow #35 for updates on this matter.
