### ISSUE TITLE
[Feature Request] Allow regex hiding of veth network interfaces

### ISSUE THREAD

**Issue by BlackDex** [AstraExt/astra-monitor#29]
## Description
As described here already #20, but for me, the interfaces keep changing there names.
Would be nice if there was a away to hide all interfaces which start with `veth`, which in this case are generated by LXD.

## Steps to Reproduce
1. Install LXD (via snapd for example)
2. Create a few LXD container's
3. Hide them via the settings
4. Restart the system
5. See new interfaces which needs to be hidden again.

## Screenshots
Same as #20

## Environment
- **Astra Monitor Version**: 5 (EGOv7)
- **GNOME Version**: 45.3
- **Operating System and Version**: Arch Linux (with latest updates)
- **Other Relevant System Information**: n/a

## Logs
n/a

## Additional Context
n/a

**Comment by ljuzig** [comment]
Done!

![Screenshot from 2024-01-20 18-25-46](https://github.com/AstraExt/astra-monitor/assets/11982322/49236c11-6c90-4ad8-b0fc-f38edef40e3b)

If you wish to test this feature you might manually install this:
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/13998693/monitor%40astraext.github.io.shell-extension.zip)

**Comment by BlackDex** [comment]
Whoho, that was fast. Ill see if i can test it in a few.

**Comment by BlackDex** [comment]
@ljuzig It works great.
Only the example seems to be incorrect though.
`^veth[\w\d]{8}` does work.

Now I'm not sure all `veth` intefaces have 8 chars appended by default, but that is at least the case for me.

**Comment by ljuzig** [comment]
@BlackDex Great, thank you for the feedback. The example was just the test case I used based off #20 output, but it's just to showcase one of the possible uses. I'm gonna change the example with `veth\w{3,16}` which might be more inclusive for all settings. Anyway the `\d` in your regex is basically useless since `\d` is already included inside `\w`.

**Comment by BlackDex** [comment]
@ljuzig That works fine to :). And indeed, `\d` is useless.
