### ISSUE TITLE
IO speed output is garbled

### ISSUE THREAD

**Issue by fedkad** [AstraExt/astra-monitor#30]
## Steps to Reproduce

1. While using the **Dash to Panel** extension use the **Astra Monitor** extension also.
2. Select to  **Show IO History Graph**  and **Show IO Speed** with 3 **Max Figures** in both **Storage** and **Network**
3. _Sometimes_ the Read/Write or Download/Upload speed values are displayed in one line, instead of two.

## Screenshots
![image](https://github.com/AstraExt/astra-monitor/assets/113997707/b5eca917-c7db-4d29-8598-e55fd4b26ea7)

## Environment

- **Astra Monitor Version**: v6
- **GNOME Version**: 45.2
- **Operating System and Version**: Ubuntu 23.10
- **Other Relevant System Information**: *Dash to Panel* extension

**Comment by ljuzig** [comment]
Thank you, Dash to Panel support is experimental right now. I'm gonna try to fix it but this is backlogged to a future version, won't make it for V7.

**Comment by fedkad** [comment]
It came to my attention that this problem is gone on most or all (?) of the times **_after screen lock / unlock_**. Related to #39...

**Comment by papampi** [comment]
Not gone for me ... 
![image](https://github.com/AstraExt/astra-monitor/assets/1108483/072fc6c7-990c-476e-b28a-e278acf86e14)

After every login from boot or even lock screen I should stop/start extension so it shows correctly

After stop/start:
![image](https://github.com/AstraExt/astra-monitor/assets/1108483/f010f648-9b08-4b95-b350-75d72d412723)

**Comment by ljuzig** [comment]
@fedkad @papampi Could you try to manually install this package and see if it gets any better?
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/14074448/monitor%40astraext.github.io.shell-extension.zip)

Thank you!

**Comment by papampi** [comment]
> @fedkad @papampi Could you try to manually install this package and see if it gets any better? [monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/14074448/monitor%40astraext.github.io.shell-extension.zip)
> 
> Thank you!

Seems like it's fixed, multiple times logged in/out and reboot and its doing ok
Thanks a lot

**Comment by fedkad** [comment]
It doesn't seem to have been fixed for me. Currently, I don't have the time to test further. When I do, I will open a new issue if necessary.

**Comment by papampi** [comment]
Yup, it seems like after reboot it still has the problem, but after a disable-enable there is no more problems even after login/logout or log in after lock screen.

**Comment by papampi** [comment]
Yes almost everytime after reboot and sometimes after login from lock screen.

**Comment by ljuzig** [comment]
Are you still experiencing this problem even with the latest version?

**Comment by papampi** [comment]
@ljuzig 
Anyway to delay loading it to test how it works with a small delay?

**Comment by papampi** [comment]
I just disabled it and add it to startup applications with 5 second sleep like this:
```bash -c 'sleep 5 ; gnome-extensions enable monitor@astraext.github.io'```
It started without problems.

**Comment by papampi** [comment]
So as a workaround until a fix ... 
Since we can not manually disable it every time at boot I added a disable/enable at startup:
```bash -c 'sleep 10 ; gnome-extensions disable monitor@astraext.github.io &&  gnome-extensions enable monitor@astraext.github.io'```

**Comment by ljuzig** [comment]
@papampi I added a way to set that directly from the extension on the preferences page. It's not a fix, but it helps to avoid using scripts or hacky scripts to delay the startup.
