### ISSUE TITLE
Gnome 46 Support

### ISSUE THREAD

**Issue by 3dsf** [AstraExt/astra-monitor#38]
## Description
Does not work with Gnome 46

## Steps to Reproduce

1. Install
2. Verify in gnome extensions that it does not work in gnome 46

## Screenshots
![Screenshot from 2024-01-24 04-49-04](https://github.com/AstraExt/astra-monitor/assets/44537624/567eb2cc-5af0-43b5-bacc-3575eb1ecd19)

## Environment

- **Astra Monitor Version**:
- **GNOME Version**: 46
- **Operating System and Version**: 
- **Other Relevant System Information**:

## Additional Context

It says the dependencies are met.  Version alpha v7 does not mention support for gnome 46, nor are there instructions to install v7 besides install via gnome extensions site (v6).
Thanks

**Comment by ljuzig** [comment]
@3dsf I made all the necessary changes to make the extension work on Gnome 46. Keep in mind that this is an alpha version and therefore further changes may be made making the extension unusable again.

![Screenshot from 2024-01-24 23-05-49](https://github.com/AstraExt/astra-monitor/assets/11982322/e888e696-3101-49fb-b5d6-c4934d84c856)

**Comment by ljuzig** [comment]
The release that will have support for Gnome 46 is Astra Monitor v8, which will be released in the next few days, if you want to try it in preview install this manually:
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/14044147/monitor%40astraext.github.io.shell-extension.zip)

**Comment by 3dsf** [comment]
Wow that was fast : )  Thanks!
I've only been using the extension a very short time but I really like it.
