### ISSUE TITLE
Sensors dropdown missing buttons for extension settings and system monitor

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#4]
## Description
All icons of the extension in the top bar have dropdowns with more system details. At the bottom of each dropdown there at least two buttons, one for opening the extension's settings and one for opening the system monitor. The Sensors dropdown is the only one that doesn't have these two buttons.

## Steps to Reproduce
1. Install and enable the extension.
2. Click on the extension's buttons in the top bar.
3. All dropdowns have at least two buttons, one for opening the extension's settings and one for opening the system monitor, except for the dropdown of Sensors.

## Screenshots
![image1](https://github.com/AstraExt/astra-monitor/assets/16370046/3d46387d-9a6f-4c41-acd8-8456642f7164)

## Environment

- **Astra Monitor Version**: 3
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

**Comment by ljuzig** [comment]
Fixed!
