### ISSUE TITLE
Overlapping metrics

### ISSUE THREAD

**Issue by DumbledoreCalrissian** [AstraExt/astra-monitor#42]
## Description

When the extension loads for the first time when booting the PC, the monitors are overlapping. By monitors I mean the vertically stacked metrics overlap instead of being stacked. The displayed metrics also sometimes overlap with the neighboring panel entries.

This isn't an intermittent issue, it happens consistently every time I boot into my PC.

## Steps to Reproduce

1. Boot into PC.
2.  Have the network and processor metrics switched on, with vertically stacked metrics.
## Screenshots

what it looks like on boot:
![image](https://github.com/AstraExt/astra-monitor/assets/97137197/2c2dd8bd-babf-4bbb-996f-0285302f176a)
![image](https://github.com/AstraExt/astra-monitor/assets/97137197/ae1b5a28-fe71-4fb5-9549-58363bb0be12)

what it looks like after turning extension off and then on:
![image](https://github.com/AstraExt/astra-monitor/assets/97137197/fa74f5a3-a666-4ac7-8feb-f04ac0e3cae5)

## Environment

- **Astra Monitor Version**: 8 EGO v11
- **GNOME Version**: 45.3
- **Operating System and Version**: Arch with kernel 6.7.1-arch1-1 
- **Other Relevant System Information**:

## Additional Context

The only way to fix this was to turn off and then on the extension. 
Also, this happens in the native gnome panel and dash-to-panel.

**Comment by ljuzig** [comment]
Same as #30. Gonna fix that now.

**Comment by ljuzig** [comment]
@DumbledoreCalrissian Could you try to manually install this package and see if it gets any better?
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/14074448/monitor%40astraext.github.io.shell-extension.zip)

**Comment by DumbledoreCalrissian** [comment]
Done. The problem seems to have been fixed.
