### ISSUE TITLE
Enhancements: Allow scroll secondary menus

### ISSUE THREAD

**Issue by papampi** [AstraExt/astra-monitor#43]
When there are too many values in secondary value screen some top and bottom values  are not visible, anyway to make them visible by scroll or other ways?
Now when I try to get the mouse to that section it goes hidden.

![Screenshot from 2024-01-28 13-46-40](https://github.com/AstraExt/astra-monitor/assets/1108483/8a16799d-9ade-4ca9-b672-8a90d441d1f2)

**Comment by ljuzig** [comment]
I can't make it scrollable cuz currently it doesn't interact with the mouse. And I don't think I want to change this behaviour because it would add too much complexity to the menus. I think I will try to detect whether the size is too big and if so, separate the data into several columns.

**Comment by ljuzig** [comment]
@papampi Try this build:
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/14076535/monitor%40astraext.github.io.shell-extension.zip)

Now the list should be split when it's too long:
![Screenshot from 2024-01-28 16-11-33](https://github.com/AstraExt/astra-monitor/assets/11982322/88b9cc3f-f47d-4d3f-97d9-e0fb016ee9e3)

**Comment by papampi** [comment]
This is much better than my suggestion to scroll.
Thank you.
