### ISSUE TITLE
Error when going to settings

### ISSUE THREAD

**Issue by giosal** [AstraExt/astra-monitor#44]
Hello,

After updating to Alpha v9 I've started encountering an error when going to Settings:

````
Error: Requiring Mtk, version none: Typelib file for namespace 'Mtk' (any version) not found

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Mtk:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
````
**Ubuntu 23.10**

**Comment by papampi** [comment]
Same issue on ubuntu 23.10

**Comment by BlackDex** [comment]
Same for Arch Linux using Gnome 45.3

**Comment by ljuzig** [comment]
Now it's fixed, thank you! I updated the release here and sent an update to [extensions.gnome.org](http://extensions.gnome.org), please update or wait for EGO to accept the update.
