### ISSUE TITLE
**VOLUNTEERS NEEDED** New Typescript build needs testing!

### ISSUE THREAD

**Issue by ljuzig** [AstraExt/astra-monitor#46]
Hi everyone, I need volunteers.
I have ported the project from plain Javascript to **Typescript**. This should have no impact whatsoever on the user as the final output should be a very similar version to the previous one. However, I need to get some feedback from people with different systems and different settings in order to check that I have not introduced regressions or errors.

I leave here a build produced by the new Typescript codebase, whoever would like to try it out and give feedback is welcome.

Thank you all for your attention and help.

UPDATED PACKAGE X2:
[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/14115145/monitor%40astraext.github.io.shell-extension.zip)

**Comment by lepa22** [comment]
Tested on Fedora 39 Workstation with X11. It does not work and Extension Manager shows this error:

> Error: Tried to construct an object without a GType

> ![image](https://github.com/AstraExt/astra-monitor/assets/16370046/6e413778-1788-460f-b102-34d19723bc4a)

# System Details Report
---

## Report details
- **Date generated:**                              2024-01-30 13:04:38

## Hardware Information:
- **Hardware Model:**                              HP HP Pavilion Notebook
- **Memory:**                                      24.0 GiB
- **Processor:**                                   Intel® Core™ i5-8250U × 8
- **Graphics:**                                    NVIDIA GeForce GTX 1050
- **Graphics 1:**                                  NVIDIA GeForce GTX 1050
- **Disk Capacity:**                               1.1 TB

## Software Information:
- **Firmware Version:**                            F.21
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.3
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.6.11-200.fc39.x86_64

**Comment by ljuzig** [comment]
@lepa22 can you show me the "see details" contents?

**Comment by lepa22** [comment]
It doesn't provide more details about the error. It is essentially the GNOME Extensions webpage for your extension. Can I provide you more info somehow?

**Comment by lepa22** [comment]
Also, if you can, please change the version in `metadata.json` to something higher than the current version, because right now, almost immediately after adding the testing version, I get asked by Extension Manager to log out to update to a newer version.

**Comment by ljuzig** [comment]
@lepa22 Thank you for your precious help. I updated the package in the Original Post, please try this new version!

**Comment by lepa22** [comment]
@ljuzig seems to be working properly now! Great work!

Just a question: In the extension's preferences I can now see vertical ellipses before the names of the items that have dropdowns (see screenshot below). I don't remember these ellipses being there in the previous versions. Are they intentional?

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/0e0d0bd6-f1d1-4d65-80a0-840e4a1c58d8)

**Comment by ljuzig** [comment]
Yes, it's being like that since a few versions. It's to visually help to recognize expansion groups from normal rows.

**Comment by lepa22** [comment]
I think that the arrows on the right are sufficient for indicating expansion groups, but since the ellipses are intended, all is well.

**Comment by topazrn** [comment]
Tested on Fedora 39 Workstation with Wayland. It's working properly!

# System Details Report
---

## Report details
- **Date generated:**                              2024-02-01 11:32:34

## Hardware Information:
- **Hardware Model:**                              ASUS PRIME H610M-E D4
- **Memory:**                                      16.0 GiB
- **Processor:**                                   12th Gen Intel® Core™ i3-12100 × 8
- **Graphics:**                                    AMD Radeon™ RX 6700 XT
- **Disk Capacity:**                               2.0 TB

## Software Information:
- **Firmware Version:**                            0601
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.3
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.13-200.fc39.x86_64
