### ISSUE TITLE
request: add additional positions in the panel

### ISSUE THREAD

**Issue by theT4mer** [AstraExt/astra-monitor#49]
Hi there! Just recently added the extension and first of all I wanted to thank you for the work. A small feature that I personally miss is the option of it being positioned in some sort of "center left", in which it is centered right in the middle of the workspace indicator and the clock. The feature exists in "TopHat" and I would love to see it here.
Greetings from Germany! ✌️

**Comment by ljuzig** [comment]
Actually there should be already a way, through "_order_" option.

1. Order 0 [LEFT]
![image](https://github.com/AstraExt/astra-monitor/assets/11982322/e6a6b237-8ee2-4fd5-9f11-5acfe38bbd32)

2. Order 1 [RIGHT]
![image](https://github.com/AstraExt/astra-monitor/assets/11982322/1ac3f392-407c-4c26-9fa0-2e949bfa2a76)

**TopHat** always set a fixed order of 1, which is _right_.
Ensure that you do not have installed extensions such as **Order Gnome Shell extensions** that will override the order set by Astra Monitor.

**Comment by theT4mer** [comment]
But are there more positions except of "directly left/right" of the existing panel object? To me it seems like there are more positions intended, but somehow do not work (yet).
[Screencast from 2024-02-01 21-35-28.webm](https://github.com/AstraExt/astra-monitor/assets/104195614/4109af30-85c4-46de-9f9f-f47a3edba94f)

**Comment by ljuzig** [comment]
@theT4mer From what I can tell from your video it works perfectly. The relevant values for you are 0 and 1 because you only have one item in those positions. Center-left for you is Center, 0. There are more values because gnome is very customizable and can have a multitude of widgets in the top panel, ie. on the left there  is someone who keeps the workspace indicator and the app menu or something else.  They are for exactly defining the position, setting the correct order in the respective widgets as well.

**Comment by theT4mer** [comment]
Ah ok then i did not understand how the setting works, I thought it would like to add some padding or so that it moves further away from the overview indicator if the values got bigger/smaller. My bad. But would it be that hard to add an additional setting controlling this, respectively (i am no dev myself, so i do not really have any experience with this)? Otherwise, as you already said, you could probably also control the position with another extension.

**Comment by theT4mer** [comment]
Ok thank you very much, that would be great!

**Comment by ljuzig** [comment]
@theT4mer done. It will be available in V10.

![Screenshot from 2024-02-02 23-34-13](https://github.com/AstraExt/astra-monitor/assets/11982322/b65f6157-2a2f-4872-92bb-c2d1d9c8539e)
