### ISSUE TITLE
CPU dropdown doesn´t show the name's processor

### ISSUE THREAD

**Issue by makecraft** [AstraExt/astra-monitor#5]
## Description
The CPU dropdown doesn´t show the model of the processor.

## Steps to Reproduce

1. Install and enable the extension.
2. Click on the extension's buttons in the top bar.
3. The drop-down menu should show in the top the processor model, which it doesn´t.

## Screenshots
![Captura desde 2024-01-12 15-23-26](https://github.com/AstraExt/astra-monitor/assets/117121011/36fbeee1-6229-4ac1-93a7-c98b6a310455)  ![imagen](https://github.com/AstraExt/astra-monitor/assets/117121011/366b3fc2-9d24-4a87-ab61-137d3d2b2da4)

## Environment

- **Astra Monitor Version**: 4
- **GNOME Version**: 45.2
- **Operating System and Version**: Manjaro Linux 23.1.1
- **Other Relevant System Information**: CPU Intel® Celeron® 2957U × 2

**Comment by ljuzig** [comment]
Interesting, does the drop-down appear if you hover where the name supposed to be with the cursor?
Can you please run "**_lscpu_**" on your terminal and paste here the output?

Thank you!

**Comment by makecraft** [comment]
Yes
![imagen](https://github.com/AstraExt/astra-monitor/assets/117121011/716420c3-cfd0-46c5-932b-cba2240c44ec)
The lscpu's output :)
![imagen](https://github.com/AstraExt/astra-monitor/assets/117121011/1d64d2b6-f2bc-4f0b-affb-a858c526eb11)
![imagen](https://github.com/AstraExt/astra-monitor/assets/117121011/4b56d0b0-d7a3-4641-a1da-14cfe0cf3238)

**Comment by ljuzig** [comment]
As already [mentioned in the code](https://github.com/AstraExt/astra-monitor/blob/a1646cc0877e1b69082ca97a72ea72b4dd631548/src/utils/utils.js#L141), lscpu might be localized. I wasn't able to reproduce it on my local machine / VMs maybe due to NixOS. Thank you for your output, it'll be very valuable, I'm gonna fix it for the next release.
