### ISSUE TITLE
After restoring to normal from full-screen app, memory meter has huge height

### ISSUE THREAD

**Issue by eboye** [AstraExt/astra-monitor#50]
## Description

After restoring to normal from full-screen app, memory meter has huge height. It looks like it's height is full screen height for a moment.

## Steps to Reproduce

1. Open the app in full screen mode (e.g. YouTube video in full-screen)
2. Wait some time (minute or so)
3. Restore the app from full-screen

## Screenshots
Cannot catch the moment it happens

## Environment

- **Astra Monitor Version**: 13
- **GNOME Version**: 45.3
- **Operating System and Version**: Arch Linux [latest]
- **Other Relevant System Information**: N/A

## Logs

N/A

## Additional Context

This does not happen every time, can't quite figure out when. I'll update the issue if I catch the pattern when it happens.

**Comment by topazrn** [comment]
Had the same issue, currently my workaround is to disable Realtime Bar and use History Graph instead.

**Comment by ljuzig** [comment]
Thank you! I'm able to reproduce that, gonna fix it soon!

**Comment by ljuzig** [comment]
This will be fixed in V10.
