### ISSUE TITLE
Graphs freeze when unfocused in GNOME 46.beta

### ISSUE THREAD

**Issue by unnamedname** [AstraExt/astra-monitor#54]
## Steps to Reproduce

1. Install this extension in GNOME OS Nightly in GNOME Boxes and the graphs freeze;
2. Move the cursor to the indicator, then the graphs update;
3. Move the cursor away from the indicator, then the graphs freeze again;

## Environment

- **Astra Monitor Version**: 10 (EGOv17)
- **GNOME Version**: GNOME 46.beta
- **Operating System and Version**: GNOME OS Nightly
- **Other Relevant System Information**:

**Comment by ljuzig** [comment]
Uhm, on the alpha everything was fine. I'm gonna test the beta soon to check if they have changed anything. Thank you for reporting!

**Comment by ljuzig** [comment]
@unnamedname Thank you very much, there was a massive bug that caused the graphs not to update when due, I had to issue a new release, you can install it manually from here:
[https://github.com/AstraExt/astra-monitor/releases/tag/v11](https://github.com/AstraExt/astra-monitor/releases/tag/v11)
or wait [EGO](https://extensions.gnome.org/extension/6682/astra-monitor/) to approve the fix.

**Comment by unnamedname** [comment]
Now it has updated to version 11(EGOv18) and the problem still exists. :face_with_head_bandage:

**Comment by ljuzig** [comment]
@unnamedname sadly that's a GNOME 46 bug, I filed an issue:
[https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7397](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7397)
