### ISSUE TITLE
GPU monitoring in topbar header

### ISSUE THREAD

**Issue by giosal** [AstraExt/astra-monitor#55]
Hello,

I saw that you've added support for AMD and NVIDIA GPU monitoring, but I don't see any options in the settings except the "Main GPU" option, which was already there.
How do I activate GPU monitoring icons?

Thank you in advance

**Comment by lepa22** [comment]
Open the extension's preferences and go to _Processors_ tab, scroll down to the _Menu_ section, click _GPU_ and select your _Main GPU_ in the dropdown:

> ![image](https://github.com/AstraExt/astra-monitor/assets/16370046/9fac54a3-b21e-4eec-a84f-034ed3289f62)

Currently the extension does not show a GPU icon on the top bar (not sure if this is on the roadmap). What this setting does is show details about the usage of your GPU in the list when you click the _Processors_ item in the top bar:

> ![image](https://github.com/AstraExt/astra-monitor/assets/16370046/44f602b6-36cd-4112-8c30-e36d57efb566)

**Comment by giosal** [comment]
Alirght, thanks a lot!
Closing the issue in this case

**Comment by ljuzig** [comment]
@giosal as already explained by @lepa22 right now GPU monitoring is menu only. But it's planned to be expanded to the top header too. There are some things on the TODO list that are more urgent for version 11, and I'm not sure if this can make it for v11 or whether has to be postponed to v12. However, it is a feature that will be implemented soon.

I am reopening the issue as an enhancement to keep track of the request and for anyone else wondering whether or not this feature is there until it lands.

**Comment by lukeab** [comment]
Would love this feature, want to use it to keep an eye on my local LLM GPU utilisation, potentially 2 gpu's our of 3 (2 cards and integrated not used), so is tick box per gpu possible to show in header bar? 
anyway, 
+1 on this feature

**Comment by ljuzig** [comment]
Working on this right now on the [gpu](https://github.com/AstraExt/astra-monitor/tree/gpu) branch. Might be ready in a week or so. Basic functionalities are already testable, I will add a build here later on so you can test it out and provide some feedback.

**Comment by ljuzig** [comment]
Release v20 closes this!
