### ISSUE TITLE
Suggestions : Bring back clean text and remove vertical triple dots from options in Astra Monitor

### ISSUE THREAD

**Issue by Anifyuli** [AstraExt/astra-monitor#56]
Hello, Mister.
I have some suggestions for you. I wish vertical triple dots on some options in Astra Monitor settings. It's come from v9 updates I guess. It make it settings look weird and incoherent with other options. I miss with v8 updates with clean options without annoying vertical triple dots. I love this extension and I suppose this extension can survive longer with GNOME updates. Thanks for read my suggestions. 
You can see it on my screenshot
![image](https://github.com/AstraExt/astra-monitor/assets/73734843/798f6b86-1ec0-430a-8a4d-d57fa910003c)

**Device info** 
OS : Ubuntu 23.04 
GNOME shell version : 45.2
Astra Monitor version : Alpha v11

**Comment by ljuzig** [comment]
I have received some more feedback on those three dots which seems to be the most hated feature ever. In the next version they will be removed and I will add a more appropriate margin to the subcategories to better distinguish the end of them.
