### ISSUE TITLE
Swap sensor doesn´t work

### ISSUE THREAD

**Issue by makecraft** [AstraExt/astra-monitor#6]
## Description
The Swap sensor should show the total and its usage

## Steps to Reproduce

1. Install and enable the extension.
2. Click on the extension's buttons in the top bar.
3. Information about the Swap should appear at the bottom of the memory dropdown menu.

## Screenshots
![Captura desde 2024-01-12 15-46-17](https://github.com/AstraExt/astra-monitor/assets/117121011/f8df5685-4fef-41da-974b-adc3aba19ad8)

## Environment

- **Astra Monitor Version**: 4
- **GNOME Version**: 45.2
- **Operating System and Version**: Manjaro Linux 23.1.1
- **Other Relevant System Information**: Partitioning Scheme: MBR

**Comment by ljuzig** [comment]
Could you please try to run "free -b" in your terminal and paste here the output?
Also, do you have a "_free_" dependency warning the the extension's settings?
I will replace _**procps**_ with _/proc/meminfo_ anyway in the next release dropping this dependency.
Swap integration is very basic and temporary right now, I will try to expand it in the next version!

**Comment by ljuzig** [comment]
It should fix itself in the next release, I dropped free and leveraged the data I already had with meminfo.
Also added some additional info:
![Screenshot from 2024-01-13 01-25-17](https://github.com/AstraExt/astra-monitor/assets/11982322/da10d710-42a5-4024-a4fd-17629c26b08a)

**Comment by makecraft** [comment]
Great!
