### ISSUE TITLE
Hover tooltips show the same contents as labels (don't enable them for shown labels?)

### ISSUE THREAD

**Issue by nekohayo** [AstraExt/astra-monitor#60]
## Description

This is a minor detail, but it probably doesn't make sense to show those tooltips on hover when the labels are configured to be shown, as the contents are identical? Unless you are planning to add more contents than that by default in the tooltips…

[Screencast from 2024-02-16 16-10-25.webm](https://github.com/AstraExt/astra-monitor/assets/479401/e84af45c-1d5e-491f-9a02-5153c9f241ea)

## Environment

- **Astra Monitor Version**: 11 (EGOv18)
- **GNOME Version**: GNOME 45.3
- **Operating System and Version**: Fedora 39

**Comment by ljuzig** [comment]
You can disable tooltips for each category if you want. Tooltips will be customizable in the future, but they are in down the line in a non-priority zone of the TODO list right now.
