### ISSUE TITLE
Allow showing free/available disk space for various partitions

### ISSUE THREAD

**Issue by nekohayo** [AstraExt/astra-monitor#61]
## Description

The extension currently allows showing a percentage used, or absolute units of used disk space, but this is unfortunately not useful to me. What would be very useful to me instead is to be able to see at a glance the free/available disk space (in megabytes and gigabytes) for various partitions, because my partitions are almost always 99% full and this is something I have to keep an eye on when doing particular operations.

For example, right now have:
* between 800 MB and 1.5 GB free space on `/` because of all the `*-debuginfo` packages I have  installed for profiling, and that's a problem because I need to apply updates in small batches instead of all in one go.
* 15 GB free on `/home`, which sounds like a lot… except when you take into consideration that it's a 2 TB drive ;)

Currently, I have to keep `gnome-system-monitor` running on the side to see this evolve in realtime. It would be nicer if I could tell Astra to show me "/ 800 MB free   /home 15 GB free" in GNOME Shell's panel.

## Environment

- **Astra Monitor Version**: 11
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39

**Comment by ljuzig** [comment]
You mean inside the menu? I can add an option to choose between "percentage", "usage value" and "free value".

**Comment by nekohayo** [comment]
Well these could be exposed within the menu too, _but_ I'd rather like them to also be available _directly on the panel_ as an alternative to the percentage labels; percentages are meaningless to me, whether at a scale of a 25 GB partition or at the scale of a 2 TB partition; labels that say something like "99%" (fullness percentage) do not help me know if I will have enough space to process the updates on `/` or to copy a certain set of files on `/home`, I need absolute free space values to be able to know that...

**Comment by ljuzig** [comment]
I will add an option to show either usage value and free value on both the top panel and in the menu, but in the top bar only the main disk will be shown. We don't support multiple disks to be shown on the top bar.

**Comment by fedkad** [comment]
> percentages are meaningless to me [...]

**Comment by ljuzig** [comment]
I added both, and added also icon alert for free values on memory and storage. For now only on headers, for tooltips and menus you'll have to wait when I'm gonna add tooltip customization and more info on each storage menu.
