### ISSUE TITLE
Failed project compilation due to updated dependency

### ISSUE THREAD

**Issue by mikusaq** [AstraExt/astra-monitor#62]
Hi, thank you for amazing extension!

I am working on Czech translation and I figured today that the newly cloned project can't be compiled.

I cloned the project and ran `npm install`. After running `i18n.sh` script I had this error output: 
![obrazek](https://github.com/AstraExt/astra-monitor/assets/94319589/4643cfc4-6513-4a9e-8164-44ba0fb376f6)

After some research I think the newly released version of girs (project dependency) has removed support for underscore properties as noted in [girs releases](https://github.com/gjsify/ts-for-gir/releases).

**Comment by ljuzig** [comment]
The [package.json](https://github.com/AstraExt/astra-monitor/blob/main/package.json) configuration allowed all girs packages to be updated to the latest minor version, but in most of them the minor version is GJS version itself. I want to keep control of when to upgrade them so I removed the update to the latest minor version setting. I recommend you sync the project to the last commit and try running the commands again.
