### ISSUE TITLE
Still can't compile the project

### ISSUE THREAD

**Issue by mikusaq** [AstraExt/astra-monitor#64]
Continuation of #62 issue.

I still can't compile the project. I think the problem is that some of the dependencies of the project are using the new 3.2.8 girs version as dependency. After `npm install` I have still many entries of the 3.2.8 version in package-lock.json.

To resolve issues with wrong versioning of dependencies (compatibility breaking changes should be only major versions), the package-lock.json could be uploaded to repository (based on [this article](https://medium.com/netscape/npm-dependency-errors-then-youre-doing-it-wrong-635160a89150)). The upload of the package-lock.json is also recommended [here](https://medium.com/helpshift-engineering/package-lock-json-the-complete-guide-2ae40175ebdd).

**Comment by ljuzig** [comment]
Thank you for reporting. While committing the package-lock.json is good practice and advisable while working in teams, this is an opensource project and I want to leave it open for anyone to be able to use their preferred package manager, such as yarn, nnpm, pnpm, etc. So uploading my package-lock.json would not benefit anyone using a different package manager. The problem must be solved at the package setting level. I will soon upload a version that will declare dependencies more explicitly and compile on any package manager.

**Comment by ljuzig** [comment]
@mikusaq please try again with the latest commit, be sure to delete Build and node_modules folder and package-lock.json or clone the project from scratch. I leave the issue open pending your feedback as to whether the problem has been successfully solved! Thank you!

**Comment by mikusaq** [comment]
I have tried it again and it works without any issue. Thank you.
