### ISSUE TITLE
UI enhancement : add auto theming on Astra Monitor

### ISSUE THREAD

**Issue by Anifyuli** [AstraExt/astra-monitor#69]
# Description
Hell, Mister. 
I have some suggestion for UI on Astra Monitor. I suggest to add auto option on theme to better integration to system theme. Because I must change theme options after changing mode from dark to light or vice versa. I attach a screenshot image to describe my mean. I wish will added to next release. Thanks for read my issue & implement it on next release

# Attachements
![image](https://github.com/AstraExt/astra-monitor/assets/73734843/6c97bd60-208f-4349-8efb-dab901b68281)

**Comment by ljuzig** [comment]
That is not feasible. That setting refers to the gnome topbar theme which is always dark, even when the theme is white. To get a light topbar you have to either install a theme that modifies the topbar or install extensions like Light Style manually. I have no way to detect if the topbar has been modified with a light theme, that setting therefore can only be manual and it's meant to meet the needs of those who have modified the topbar style to light. For instance, in your screen, although the theme is light, your topbar is still dark.

**Comment by Anifyuli** [comment]
I think it can implement if I enable light shell theme like Yaru light theme in my case

**Comment by ljuzig** [comment]
Light themes usually have dark topbar (like the one in your screen above). Sadly GNOME does not give me an API or a simple way to know if the topbar and the menus of the topbar are light or dark so the user has to manually select that since the standard for gnome is dark. I will try to check with the gnome community to see if there is a way to overcome this problem.

**Comment by Anifyuli** [comment]
Ok, I'll wait your next updates, Dude. Thanks for your dedication to this extension
