### ISSUE TITLE
History graph dimensions

### ISSUE THREAD

**Issue by tstdin** [AstraExt/astra-monitor#7]
Thank you for the great extension! I am a long time user of the system-monitor and this is the first time I am considering to switch to something else.

The thing which I would love to see is the ability to configure the dimensions of the history graph. At the moment I feel like it is less readable compared to the system-monitor.

1. **top and bottom margins**: I have the impression that there is too much space wasted on the top and bottom margins, which could be used to have more readable graph (maybe there could be an option to turn off the top+bottom margins in the configuration).
2. **width**: the width is too narrow for my taste. It would be nice to have the option of e.g. double the width.

*Screenshot showing the comparison between astra-monitor and system-monitor**:
![image](https://github.com/AstraExt/astra-monitor/assets/25065143/cb0ccb28-2241-403f-9382-d81adab606c9)

Keep up with the great work!

**Comment by ljuzig** [comment]
Thank you, it makes me very happy to know that my extension may be worth a switch from long-standing extensions.
Customization is one of the main drives of the upcoming versions, starting with icons, colors and size of the graphs/bars. As for margins and other style things, I'm still not sure if they will make it into the next version, but anyway the goal is to deploy them by the end of January.

**Comment by ljuzig** [comment]
History Graph Width customization is coming for sure in v4.
Settings do work in real-time, you are able to check the result while editing the value.
![Screenshot from 2024-01-14 15-38-47](https://github.com/AstraExt/astra-monitor/assets/11982322/b900dd7d-dc17-42e3-b0e4-3ebcab3976a8)

**Comment by ljuzig** [comment]
And also Header's height/margins.
![Screenshot from 2024-01-14 20-41-40](https://github.com/AstraExt/astra-monitor/assets/11982322/0cd2dcb2-9ef1-4369-b59d-912817538a68)
