### ISSUE TITLE
Enhancement: Add import and export settings option

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#71]
## Description
As the extension is very flexible, with many new features and settings added regularly, I think it makes sense to have an option to export the user's current settings in a file that can also be imported, so that the user shouldn't have to go through the hassle of reconfiguring the extension in a new installation once they have settled with the settings they like.

I'm pretty sure that you have already thought (and probably planned) of this, but I'm just adding this post as a reminder.

**Comment by fedkad** [comment]
This may also be helpful in bug reports.

**Comment by ljuzig** [comment]
Added to the [Roadmap](https://github.com/AstraExt/astra-monitor#roadmap). This should land with the Beta release in the next few days.
