### ISSUE TITLE
Enhancement: Add system load Average

### ISSUE THREAD

**Issue by papampi** [AstraExt/astra-monitor#73]
It would be nice to have system load averages in CPU section too.
We have system uptime so we can have system load averages as well.

**Comment by fedkad** [comment]
I think, what is asked is the same as the first item in #16.

**Comment by ljuzig** [comment]
I added initial support for Load average monitoring. The graph will be added when there will be support for optional continuous menu resource monitoring after the beta.

**Comment by fedkad** [comment]
**Load Average** data was added directly to the *Processors* menu. In terms of conserving space, I would recommend adding it as a popup window which will be displayed when the mouse hovers over the **System uptime** section of the Processors menu. 

Also in terms of *consistent capitalization*, should the the **A** in **Load Average** be in lower case? Note: There are similar inconsistent capitalizations elsewhere too.

**Comment by ljuzig** [comment]
I fixed "Load average" inconsistency. For now I keep it in the main menu, when we'll have too many options I might move it to System uptime as suggested!

**Comment by papampi** [comment]
Thanks a lot for adding it.

Maybe a graph for it too?
Although CPU usage graph shows an estimate of system load history, but a "load average graph" may be useful too.
