### ISSUE TITLE
Enhancement: Add feature to set colours for all monitors at once

### ISSUE THREAD

**Issue by zeerayne** [AstraExt/astra-monitor#74]
## Description

It will be useful for me to have a feature that allows me to set up colors once and apply it to every monitor/graph in the extension.
Colors which I wish to setup are:
1. Main & secondary color for bars
2. Main & secondary color for graphs
3. Icon color & icon alert color

Thoughts: maybe it can be performed as setting like "use same colors for all monitors", which will allow to setup colors on general tab.

For now if I want to change a color I should change it in every monitors's graph separately. It is working, but taking me some time to adjust every time I with to change colors.

**Comment by fedkad** [comment]
**Just a comment:** The settings tabs are getting more and more complex. A method to simplify them will be needed in the near future.

**Comment by ljuzig** [comment]
@zeerayne In the next release there will be a global setting for main and secondary colors to overwrite them all at once. You will still be able to customize each of them if needed.

**Comment by ljuzig** [comment]
@fedkad We have a large amount of customization options, and many more will be added later, and it starts to become challenging to make the settings panel clear and simple. As of now I don't feel like it is a major hurdle for our users and I don't think it's worth wasting too much time to revamp it, in the future we will see if it becomes problematic.
