### ISSUE TITLE
Some feedback on sensor issues and feature suggestions

### ISSUE THREAD

**Issue by WhoChangedMyCode** [AstraExt/astra-monitor#75]
## Description
- Problem 1: The sensor occasionally loses monitoring data, like the following picture: 
![Screenshot from 2024-03-07 16-46-23](https://github.com/AstraExt/astra-monitor/assets/76393980/4c3e1aa7-8310-40f3-9d91-f59f8fdde4f5)
  To restore normal, you have to close the plug-in and reopen it.

- Problem 2: The data monitored by the sensor is sometimes incomplete, like the following:
  ![Screenshot from 2024-03-07 16-41-18](https://github.com/AstraExt/astra-monitor/assets/76393980/28e32937-ebba-4874-88f3-8f884cedb546)

## Steps to Reproduce

I'm sorry, I don't know how to reproduce this. I'm frustrated too.
If you need more data to solve your problem, I'm happy to help!

## Environment

- **Astra Monitor Version**: Alpha v13
- **Other Relevant System Information**:
![Screenshot from 2024-03-07 17-01-41](https://github.com/AstraExt/astra-monitor/assets/76393980/6da8feec-1bca-425c-aba2-8627cc3edbc3)

## Some feature suggestions
For sensor monitoring, here are some of the new features I'm looking forward to:
1.  I would like to add History Graph (refer to Processors)
  History Graph can let me know the change of data in a period of time, which is useful for me, and I think it is more unified with Processors, Memory, etc. after adding History Graph.

2. Add icon alarm (refer to Processors)

**Comment by ljuzig** [comment]
As you can see from our [Roadmap](https://github.com/AstraExt/astra-monitor?tab=readme-ov-file#roadmap) I'm about to adding hwmon source before the next release which should drop the lm-sensors requirement and improve a lot sensors monitoring. The graph is still not in the roadmap yet but I will try to make it fit in, by the end of March possibly!

**Comment by 3dsf** [comment]
I could feel my radiator exhaust unexpectedly and looked up to find out I was experiencing something similar 
(I'm not running rawhide currently)

you probably already have it fixed, but this is what i was seeing in my journalctl (a million of these)
```
Mar 09 08:46:12 fedora gnome-shell[3106]: Error
                                          error@file:///home/3dsf/.local/share/gnome-shell/extensions/monitor@astraext.github.io/src/utils/utils.js:117:23
                                          updateSensorsData@file:///home/3dsf/.local/share/gnome-shell/extensions/monitor@astraext.github.io/src/sensors/sensorsMonitor.js:107:19
                                          async*makeCancellable/promise</timeoutId<@file:///home/3dsf/.local/share/gnome-shell/extensions/monitor@astraext.github.io/src/utils/cancellableTaskManager.js:50:17
                                          setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9
                                          @resource:///org/gnome/shell/ui/init.js:21:20
                                             Astra Monitor ERROR: sensorsDataValue is undefined
Mar 09 08:46:15 fedora gnome-shell[3106]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                            @resource:///org/gnome/shell/ui/init.js:21:20
```
and at least one of these
```
Mar 09 09:40:10 fedora gnome-shell[3106]: Error
                                          error@file:///home/3dsf/.local/share/gnome-shell/extensions/monitor@astraext.github.io/src/utils/utils.js:117:23
                                          updateSensorsData@file:///home/3dsf/.local/share/gnome-shell/extensions/monitor@astraext.github.io/src/sensors/sensorsMonitor.js:107:19
                                          async*makeCancellable/promise</timeoutId<@file:///home/3dsf/.local/share/gnome-shell/extensions/monitor@astraext.github.io/src/utils/cancellableTaskManager.js:50:17
```

**Comment by ljuzig** [comment]
`lm-sensors` will be deprecated in the next version in favor of `hwmon` which requires no dependency and should be embedded in every distro. This has a several positive impacts: better performance, more reliability, no dependence as already mentioned, and easier future maintenance.

In the next version you will see both:
[lm-sensors] Sensor Name - edge - temp1_input
[hwmon] Sensor Name - Edge - Temp1 - Input
or something similar.

You may already switch to `hwmon` or keep `lm-sensor` if you face some issue, but `hwmon` should already be better.
In the following release (which should be the beta release) `lm-sensors` will be removed.

**Comment by ljuzig** [comment]
I just released v14, please test the new hwmon sensors and give me a feedback if all problems get resolved.
Remember to manually update **ALL** your sensors from the settings from [lm-sensors] to [hwmon].

Thank you!

**Comment by 3dsf** [comment]
Thanks, looks good to me. 
hwmon temps populated; looks like i had the same temps populated as I had with lm-sensor 
I had to log out of the session for the update to take affect.
