### ISSUE TITLE
[Enhancement/Bug] Problem with dual AMD GPU only the iGPU visible

### ISSUE THREAD

**Issue by Andorreta** [AstraExt/astra-monitor#76]
## Description
Hi, i have a dual AMD GPU setup (ryzen APU + NAVI dGPU). I can't see the dGPU unlike the Nvidia dGPU that i saw in other people screenshots. And i don't have the option to select the dGPU as the main GPU.

## Steps to Reproduce
Open the Main GPU dialog in the CPU options or the CPU menu of the extension

## Screenshots
CPU menu:
![CPU menu](https://github.com/AstraExt/astra-monitor/assets/8407576/5dc0bd54-e7f9-4372-9991-5884bdf04f4e)

CPU options -> Main GPU:
![CPU options -> Main GPU](https://github.com/AstraExt/astra-monitor/assets/8407576/38625ee6-4f75-4709-88bd-ddbbd7659e43)

System information:
![System information](https://github.com/AstraExt/astra-monitor/assets/8407576/80927672-2669-48a5-83a3-a08cea115559)

## Environment
- **Astra Monitor Version**: Astra 13
- **GNOME Version**: 45 stable (soon 46)
- **Operating System and Version**: Arch Linux 
- **Other Relevant System Information**: It's a laptop (ASUS ROG G15 513QY Advantage Edition) with the main display connected directly to the dGPU using the USB-c alt mode DP. (I'm using a big external display and have the laptop disaply disabled)
- All the prerequisites are installed correctly.

## Logs
- There're no errors or logs.

## Additional Context
I have the zenpower, amdgpu, lm_sensors and asus modules loadded. So extensions like Vitals show correctly the 2 gpus and the temps and data from each one.

If needed i can download and test or contribute programming :D

**Comment by ljuzig** [comment]
Can you share the full output of `lspci -nnk`?

**Comment by Andorreta** [comment]
Sure, no problem :D

00:00.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne Root Complex [1022:1630]
	Subsystem: ASUSTeK Computer Inc. Renoir/Cezanne Root Complex [1043:16c2]
00:00.2 IOMMU [0806]: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne IOMMU [1022:1631]
	Subsystem: ASUSTeK Computer Inc. Renoir/Cezanne IOMMU [1043:16c2]
00:01.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge [1022:1632]
00:01.1 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Renoir PCIe GPP Bridge [1022:1633]
	Subsystem: ASUSTeK Computer Inc. Renoir PCIe GPP Bridge [1043:16c2]
	Kernel driver in use: pcieport
00:02.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge [1022:1632]
00:02.1 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge [1022:1634]
	Subsystem: ASUSTeK Computer Inc. Renoir/Cezanne PCIe GPP Bridge [1043:16c2]
	Kernel driver in use: pcieport
00:02.2 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge [1022:1634]
	Subsystem: ASUSTeK Computer Inc. Renoir/Cezanne PCIe GPP Bridge [1043:16c2]
	Kernel driver in use: pcieport
00:02.3 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge [1022:1634]
	Subsystem: ASUSTeK Computer Inc. Renoir/Cezanne PCIe GPP Bridge [1043:16c2]
	Kernel driver in use: pcieport
00:02.4 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge [1022:1634]
	Subsystem: ASUSTeK Computer Inc. Renoir/Cezanne PCIe GPP Bridge [1043:16c2]
	Kernel driver in use: pcieport
00:08.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge [1022:1632]
00:08.1 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus [1022:1635]
	Subsystem: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus [1022:1635]
	Kernel driver in use: pcieport
00:14.0 SMBus [0c05]: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller [1022:790b] (rev 51)
	Subsystem: ASUSTeK Computer Inc. FCH SMBus Controller [1043:16c2]
	Kernel driver in use: piix4_smbus
	Kernel modules: i2c_piix4, sp5100_tco
00:14.3 ISA bridge [0601]: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge [1022:790e] (rev 51)
	Subsystem: ASUSTeK Computer Inc. FCH LPC Bridge [1043:16c2]
00:18.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 0 [1022:166a]
00:18.1 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 1 [1022:166b]
00:18.2 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 2 [1022:166c]
00:18.3 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 3 [1022:166d]
	Kernel driver in use: zenpower
	Kernel modules: k10temp, zenpower
00:18.4 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 4 [1022:166e]
00:18.5 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 5 [1022:166f]
00:18.6 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 6 [1022:1670]
00:18.7 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 7 [1022:1671]
01:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 XL Upstream Port of PCI Express Switch [1002:1478] (rev c3)
	Kernel driver in use: pcieport
02:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 XL Downstream Port of PCI Express Switch [1002:1479]
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 XL Downstream Port of PCI Express Switch [1002:1479]
	Kernel driver in use: pcieport
03:00.0 Display controller [0380]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c3)
	Subsystem: ASUSTeK Computer Inc. Radeon RX 6800M [1043:16c2]
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
03:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21/23 HDMI/DP Audio Controller [1002:ab28]
	Subsystem: ASUSTeK Computer Inc. Navi 21/23 HDMI/DP Audio Controller [1043:16c2]
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
04:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 15)
	Subsystem: ASUSTeK Computer Inc. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [1043:208f]
	Kernel driver in use: r8169
	Kernel modules: r8169
05:00.0 Network controller [0280]: Intel Corporation Wi-Fi 6E(802.11ax) AX210/AX1675* 2x2 [Typhoon Peak] [8086:2725] (rev 1a)
	Subsystem: Intel Corporation Wi-Fi 6 AX210 160MHz [8086:0024]
	Kernel driver in use: iwlwifi
	Kernel modules: iwlwifi
06:00.0 Non-Volatile memory controller [0108]: Sandisk Corp WD Blue SN570 NVMe SSD 2TB [15b7:5025] (rev 01)
	Subsystem: Sandisk Corp WD Blue SN570 NVMe SSD 2TB [15b7:5025]
	Kernel driver in use: nvme
	Kernel modules: nvme
07:00.0 Non-Volatile memory controller [0108]: SK hynix Gold P31/BC711/PC711 NVMe Solid State Drive [1c5c:174a]
	Subsystem: SK hynix Gold P31/BC711/PC711 NVMe Solid State Drive [1c5c:174a]
	Kernel driver in use: nvme
	Kernel modules: nvme
08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c4)
	Subsystem: ASUSTeK Computer Inc. Radeon Vega 8 [1043:16c2]
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
08:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller [1002:1637]
	Subsystem: ASUSTeK Computer Inc. Renoir Radeon High Definition Audio Controller [1043:16c2]
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
08:00.2 Encryption controller [1080]: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor [1022:15df]
	Subsystem: ASUSTeK Computer Inc. Family 17h (Models 10h-1fh) Platform Security Processor [1043:16c2]
	Kernel driver in use: ccp
	Kernel modules: ccp
08:00.3 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1 [1022:1639]
	Subsystem: ASUSTeK Computer Inc. Renoir/Cezanne USB 3.1 [1043:201f]
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci
08:00.4 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1 [1022:1639]
	Subsystem: ASUSTeK Computer Inc. Renoir/Cezanne USB 3.1 [1043:201f]
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci
08:00.5 Multimedia controller [0480]: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor [1022:15e2] (rev 01)
	Subsystem: ASUSTeK Computer Inc. ACP/ACP3X/ACP6x Audio Coprocessor [1043:104f]
	Kernel modules: snd_pci_acp3x, snd_rn_pci_acp3x, snd_pci_acp5x, snd_pci_acp6x, snd_acp_pci, snd_rpl_pci_acp6x, snd_pci_ps, snd_sof_amd_renoir, snd_sof_amd_rembrandt, snd_sof_amd_vangogh, snd_sof_amd_acp63
08:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller [1022:15e3]
	DeviceName: HD Audio Controller
	Subsystem: ASUSTeK Computer Inc. Family 17h/19h HD Audio Controller [1043:104f]
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

[lspci.txt](https://github.com/AstraExt/astra-monitor/files/14547080/lspci.txt)

**Comment by ljuzig** [comment]
Ok, that's a bug! I'm gonna fix it now, thank you!

**Comment by Andorreta** [comment]
> Ok, that's a bug! I'm gonna fix it now, thank you!

Thanks to you. If I can help with anything else, let me know 😁

**Comment by ljuzig** [comment]
Now it's fixed. You'll have to wait the next release or pack the extension yourself from the repo.

![Screenshot from 2024-03-09 17-51-59](https://github.com/AstraExt/astra-monitor/assets/11982322/ce212e7b-18b5-4cc6-b03a-8db9bc818ed2)
