### ISSUE TITLE
Issues with Import/Export Settings

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#79]
## Description
It's great to see _Import/Export Settings_ being added in the latest release (which is another great release!). However, I have spotted some issues, which I will list all below in this issue. The numbers in the following ordered list are used to indicate issues, not steps.

1. _Import/Export Settings_ are contained in the _Utility_ section of the _About_ tab, which in my opinion is not the best place for these settings. It took me a while after seeing in the changelog that this feature was implemented to actually find it. The best place for the whole _Utility_ section would be in the _General_ tab, since these are indeed generic settings and the _About_ tab is expected to contain mainly informational stuff about the extension. All in all, this is not really a bug, rather a design preference, which you may or may not want to change, but I'm still mentioning for your consideration.

2. After clicking _Export Settings_, a dialog of my home directory opens, as you can see in the following screenshot:
   
    ![image](https://github.com/AstraExt/astra-monitor/assets/16370046/d14acab0-799c-4df3-8dbd-9e971bbd7f1b)

    The first issue with this is that the _Name_ textbox on the top of the dialog window is empty, no name for the export file is suggested. It is important to have a name suggested there, not only for ease of use, but, more importantly, so users can know what type of extension the exported file is supposed to have!

    The first time I exported the settings in a `.txt` file. Inspecting the file I saw that it was a JSON file, so I changed the extension to `.json` to be able to then import it. So the _Name_ textbox should by default suggest a name like `astra-settings-202403121123.json` or something similar (the numerical part is the current date and time, so that someone could easily select a file to import based on the datetime).

    Additionally, the type selection filter on the bottom right of the dialog is currently empty:

    ![image](https://github.com/AstraExt/astra-monitor/assets/16370046/60b76c65-6e08-475b-9929-8841f17ab62d)

    Since the exported file must be a JSON file, it should be used to only allow for showing and saving JSON files.
  
3.  After clicking _Import Settings_, a dialog opened in the home directory, but was not showing the `.txt` I had initially saved. I could however search for the file and then select it and click _Open_ to import it:

    ![image](https://github.com/AstraExt/astra-monitor/assets/16370046/113a5227-450e-4c23-89f4-790fb5da01d3)

    As expected, it wasn't actually imported. The file selection dialog just closed and I had no indication of what happened.

    After I changed the extension of the exported settings file to `.json`, the file was shown in the home directory and I could correctly import it and the settings were correctly applied.

    As in the export case I mentioned above, the  type selection filter on the bottom right of the dialog should only allow listing of JSON files.

## Environment

- **Astra Monitor Version**: 14 (EGOv23)
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

**Comment by ljuzig** [comment]
These suggestions make a lot of sense, I'm going to improve/solve all listed issues in the next build. Thank you!

**Comment by fedkad** [comment]
I am completely in agreement with the _all_ the findings and suggestions of @lepa22.

I would also like to add the following:

* The file contents are in JSON format, but they are _all in a single line_ and even there is _no end of line_ at the end of the file. It would be better for them to be formatted like the `jq <settings.json` command will display.
* The settings seem to be ordered randomly. It would be better to output them in some order, even in name order would be more helpful.

**Comment by ljuzig** [comment]
I have implemented almost everything requested above. As for moving the export/import from About to General, I'm not quite sure because in General it would go below everything in a fairly full window already, ideally a new tab specifically for that would be better but it seems to me that it would be the only thing that would go there for now, I'm still going to consider this for eventual refactoring of the settings. The json keys are now sorted by name but I don't think it's worth formatting them or getting into developing a formatter just for this specific function.

**Comment by lepa22** [comment]
Thanks for the fixes! However, the JSON filter does not work totally as intended yet, since it also lists at least `.ipynb` files, as you can see in the screenshot:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/fc99e68b-2c10-46c4-bffe-b603695164d9)
