### ISSUE TITLE
Add About tab or menu

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#8]
## Description
The extension is currently missing an *About* tab or, to keep the interface cleaner and focused on the top bar contents, a hamburger menu with an *About* option. This would be a nice way to provide author credits and donation links, and also make it easier for users of the extension to find the version they are using.

The last point is particularly important for bug reporting, since you need to know the exact version a user that reports a bug is using. For example, for my last bug reports I was unsure about the version of the extension that I should mention, so I used the version shown in [GNOME Extensions](https://extensions.gnome.org/extension/6682/astra-monitor/), which was version 3. However, it seems that in GitHub the extension was on v1. Right now, [GNOME Extensions](https://extensions.gnome.org/extension/6682/astra-monitor/) shows version 4, while on GitHub it is v2.

It is obvious that version reporting could be confusing as it currently is, so an *About* option can help alleviate this issue. After that you could also update your bug reporting template to inform the users where to find the extension's version.

**PS:** Your extension looks awesome and I have already replaced Vitals with it! Keep up the good work! :)

**Comment by ljuzig** [comment]
Yes, indeed having a clear indication of the extension's version would help a lot. I added that in the TODO on the next release. EGO changes the metadata with an internal version that helps them to keep track of the revision process, but that should be in metadata only. [Here](https://extensions.gnome.org/extension/6682/astra-monitor/) I actually see 45 - 2 as version. Anyway I will add an about page or a clear indication of the current version, Thank you!
