### ISSUE TITLE
Tooltip Sensor items alignment is broken

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#80]
## Description
The alignment of the _Tooltip Sensor #_ items of the _Tooltip_ section of the _Sensors_ tab in the extension's preferences is broken. You can see what I mean in the screenshot below.

## Steps to Reproduce

1. Install and enable the extension.
2. Open preferences, then go to the _Sensors_ tab and expand _Tooltip Sensor #_.
3. The "Source" label is broken and the text is shown vertically.

## Screenshots
![image](https://github.com/AstraExt/astra-monitor/assets/16370046/aa60d8eb-da24-4714-8487-f7e172aad4d3)

## Environment

- **Astra Monitor Version**: 14 (EGOv23)
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

**Comment by fedkad** [comment]
Same problem in **GPU** section:

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/0bbdf87d-d828-42fb-a874-66be9a5fbcbf)

**Comment by lepa22** [comment]
Hmmm... I don't have the issue in _GPU_:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/630b323e-cac8-471e-b90f-aadee7a3e5ec)

I wonder if this could also be related to case 4 of issue https://github.com/AstraExt/astra-monitor/issues/68.

**Comment by fedkad** [comment]
> Hmmm... I don't have the issue in _GPU_:
> 
> I wonder if this could also be related to case 4 of issue #68.

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/8ba387a8-37e0-47cb-a51d-c3c2d2b662b2)

**Comment by lepa22** [comment]
Nice GPU! :smirk: 

So it seems that the cause of the issue is that the dropdown's width is equal to the maximum length of its items.

Here is the longest item for my _Tooltip Sensor #_ dropdown:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/3759dcd7-65bb-42d8-8250-ec7775160b1e)

**Comment by ljuzig** [comment]
Fixed, thank you all for reporting!
