### ISSUE TITLE
Sensor cannot display data after removing lm_sensors.

### ISSUE THREAD

**Issue by WhoChangedMyCode** [AstraExt/astra-monitor#81]
## Description

After I upgraded Astart Monitor from Alpha v13 to Alpha v14, I removed lm_sensors (sudo dnf remove lm_seonsors) and then realized that Sensor was not displaying the data：
![Screenshot from 2024-03-12 17-45-13](https://github.com/AstraExt/astra-monitor/assets/76393980/493550be-8416-4262-a611-a68661fc59fc)

even though I had changed Data Sources to Hwmon:
![Screenshot from 2024-03-12 19-23-04](https://github.com/AstraExt/astra-monitor/assets/76393980/2fc1b65a-48f8-47fd-a83f-8bfd9774742b)
![Screenshot from 2024-03-12 19-23-45](https://github.com/AstraExt/astra-monitor/assets/76393980/42e72c39-27c3-47c7-9b34-acb9f559db88)
![Screenshot from 2024-03-12 19-24-23](https://github.com/AstraExt/astra-monitor/assets/76393980/9c17241b-17f9-46bc-9a9f-b2095b86f49c)

I tried restarting the computer or reinstalling Astart Monitor, but it didn't help.

Now for Sensor to work properly, I have to install lm_seonsors (even if I set the Data Source to hwmon)：
![Screenshot from 2024-03-12 19-38-18](https://github.com/AstraExt/astra-monitor/assets/76393980/1d9a0a9f-9839-448c-83fc-ac87283c5b9c)

## Steps to Reproduce

1. Upgrade Astart Monitor from Alpha v13 to Alpha v14
2. sudo dnf remvoe lm_seonsors

## Environment

- **Astra Monitor Version**: Alpha v14
- **Other Relevant System Information**:
![Screenshot from 2024-03-12 19-25-24](https://github.com/AstraExt/astra-monitor/assets/76393980/65b29b57-6ca7-4447-96c0-47d8a6e4bcb9)

**Comment by ljuzig** [comment]
Very interesting bug, I'm not able to reproduce this. I can successfully remove `lm-sensors` and be able to see sensor data. What's being shown in the sensors menu? Clicking on the temperature icon are you able to see all your sensors?
Do you see any warning in "Dependencies" inside General tab in Settings panel?

can you run these 2 command in your terminal and paste here the output?
`ls /sys/class/hwmon`
`cat /sys/class/hwmon/hwmon0/name`

While testing I found a minor bug that shouldn't cause this issue tho.

**Comment by ljuzig** [comment]
If you want to test the build with the minor bug fixed you can try to install this manually and see if something does change:
```bash
gnome-extensions install --force monitor@astraext.github.io.shell-extension.zip
```
Be sure to logout/login or restart after the install.

[monitor@astraext.github.io.shell-extension.zip](https://github.com/AstraExt/astra-monitor/files/14572581/monitor%40astraext.github.io.shell-extension.zip)

**Comment by WhoChangedMyCode** [comment]
Oh, yeah! After I installed it manually and restarted my computer, it works fine now for once!
![Screenshot from 2024-03-12 21-46-53](https://github.com/AstraExt/astra-monitor/assets/76393980/7427e0ee-c64e-4ecc-85c2-316e4713ac52)

And to double check, I installed the V14 version again via [gnome extensions web page](https://extensions.gnome.org/extension/6682/astra-monitor/ ) and the Sensor doesn't work.

![Screenshot from 2024-03-12 21-54-50](https://github.com/AstraExt/astra-monitor/assets/76393980/340e9c11-b111-4af3-ac6e-28a3a1c1f790)

I hope a new version that fixes this problem will be released soon ❤️

**Comment by ljuzig** [comment]
I mark this as fixed. As soon as I fix all bugs, I'm gonna release a beta. Hopefully very soon!
