### ISSUE TITLE
Option to display network download/upload horizontally

### ISSUE THREAD

**Issue by ChloeDawn** [AstraExt/astra-monitor#82]
I would personally like to have the download and upload speeds displayed in horizontal alignment with the same font size as usage percentages, instead of the current smaller font size vertical alignment.

**Comment by ljuzig** [comment]
This will be done with "Advanced Network Monitoring", please check our [Roadmap](https://github.com/AstraExt/astra-monitor?tab=readme-ov-file#roadmap). Thank you!
