### ISSUE TITLE
Wrong highlighting for Sensors on hover information

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#84]
## Description
In the on hover information of all menus, the labels are gray and use italic fonts while the values are white, giving more focus to the values. In the on hover information of _Sensors_, however, the situation is exactly the opposite: the labels are white while the values are gray and use italic fonts.

## Steps to Reproduce
1. Install and enable the extension.
2. Click on an item on the top bar, for example _CPU_, and move your cursor to a menu item that displays information on hover, for example on the _CPU info_ item. The labels of the items there are gray and use italic fonts while the values are white.
3. Now click on the _Sensors_ item on the top bar and move your cursor to a menu item that displays information on hover. Observe that the labels of the items there are white while the values are gray and use italic fonts.

## Screenshots
_CPU_ item on top bar showing correct font colors and styles for on hover information:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/475185d8-542f-41ab-a2d4-6d1b93d7ba1b)

_Sensors_ item on top bar showing wrong font colors and style for on hover information:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/6afc4b72-2580-4e5c-a677-ee32d7dfb34a)

## Environment

- **Astra Monitor Version**: 14 (EGOv23)
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

**Comment by ljuzig** [comment]
Done, also added more useful info in the list like the type of sensor.
