### ISSUE TITLE
Recommendations for optimizing the display of network monitoring data

### ISSUE THREAD

**Issue by WhoChangedMyCode** [AstraExt/astra-monitor#85]
When there is no network activity, the current version(15) is displayed with a "-", like this:
![Screenshot from 2024-03-13 12-10-53](https://github.com/AstraExt/astra-monitor/assets/76393980/e4c18a86-848a-4a0a-bcbd-b0fe9425a913)

I personally recommend using "0" instead for a more intuitive look (and using "-" means it reminds me of the previous situation where the Sensor didn't work properly)

**Comment by ljuzig** [comment]
There are several reasons why I chose to show `-` instead of `0`, however I understand that it may be a personal need or preference so I will still add an option to show 0 instead of `-`.
