### ISSUE TITLE
User's usage is not shown in "CPU Cores Usage Info" pop up when "Core Bars Breakdown" is enabled

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#86]
## Description
After the last update, the *CPU Cores Usage Info* bars only show the system's usage (with red color), not the user's usage (blue color). It's as if the system's usage is above a ghost user usage (see screenshots to understand what I mean). Normally, the user's usage in blue color should be below the system's usage.

## Steps to Reproduce
1. Install and enable the extension.
2. Open the extension's preferences.
3. In the _Processors_ tab enable _Core Bars Breakdown_.
4. Click on the _CPU_ item on the top bar and hover over the history graph.
5. In the *CPU Cores Usage Info* pop up observe that only the system's usage (with red color) appears above a not-shown user's usage (which should be in blue color).

## Screenshots

![Screenshot from 2024-03-14 14-57-23](https://github.com/AstraExt/astra-monitor/assets/16370046/5b9100c7-7b67-40f2-ae3e-1a94780646ba)

## Environment

- **Astra Monitor Version**: 15 (EGOv24)
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

**Comment by lepa22** [comment]
The issue is most likely related to https://github.com/AstraExt/astra-monitor/issues/83.

**Comment by ljuzig** [comment]
Fixed, thank you!
