### ISSUE TITLE
Bug : Panel Box option on General -> Visualization menu can't change Astra Monitor position and order on top panel

### ISSUE THREAD

**Issue by Anifyuli** [AstraExt/astra-monitor#88]
## Description

Hello, Mister. I want to report a bug, it is Astra Monitor can't change position after update to v15. I add [this extension](https://extensions.gnome.org/extension/6310/window-title-is-back/) on left side of panel

## Steps to Reproduce

1. Install latest version of Astra Monitor
2. Add [Window title is back](https://extensions.gnome.org/extension/6310/window-title-is-back/) extension
3. Change it position in General -> Visualization -> Panel Box -> Position (I choose left)
4. Change it order in General -> Visualization -> Panel Box -> Order (I add 2 integer value)
5. Nothing changes appear

## Screenshots

![image](https://github.com/AstraExt/astra-monitor/assets/73734843/5e78db0b-e32a-4d0a-ad86-cbd02241af77)

## Environment

- **Astra Monitor Version**: v15(EGOv24)
- **GNOME Version**: 45.2
- **Operating System and Version**: Ubuntu 23.10 
- **Other Relevant System Information**: Kernel version 6.5.0-25-generic, screen size 1366x768

## Logs

I haven't any idea how to add logs in here

## Additional Context

I wish it can fixed soon as possible

**Comment by ljuzig** [comment]
It's working pretty fine on my end:
![Screenshot from 2024-03-18 19-18-02](https://github.com/AstraExt/astra-monitor/assets/11982322/c9d444b3-0332-4dba-a8b2-380285750b9f)

Sadly sometimes it's beyond my control, other extensions might change this behaviour. If you want a more fine tuned top bar ordering I suggest you to add [Order Gnome Shell extensions](https://extensions.gnome.org/extension/2114/order-gnome-shell-extensions/) or any other topbar ordering management extension.

**Comment by Anifyuli** [comment]
Nice info, Mister. Thanks. I'm using [Top Bar Organizer](https://gitlab.gnome.org/julianschacher/top-bar-organizer) extension. I think I can't change change it position because this extension
