### ISSUE TITLE
Does not install on Debian Sid (yet GNOME 46)

### ISSUE THREAD

**Issue by prog-amateur2** [AstraExt/astra-monitor#89]
## Description
Hello, I'm on Debian Sid. My system settings tell me that I'm on GNOME 46. However, I can't install the extension, due to an incompatibility (details in logs). What do you think? Thanks a lot!

## Steps to Reproduce

1. Go to extensions
2. Browse content (search Astra Monitor)
3. See the incompatibility and even after installing despite the warning, it does not work (of course)

## Screenshots (GNOME details & other extensions just for information)
![image](https://github.com/AstraExt/astra-monitor/assets/60101083/68ceec0c-f6ee-49d3-91af-607213e8f43a)
![image](https://github.com/AstraExt/astra-monitor/assets/60101083/bf7d8b6b-498e-4c2e-963e-c13d3776e23b)

## Environment
- **Astra Monitor Version**: 20
- **GNOME Version**: 46
- **Operating System and Version**: Debian Sid (Debian GNU/Linux trixie/sid)
- **Other Relevant System Information**: no tweak

## Logs
```
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
  async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:187:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:207:19
  start@resource:///org/gnome/gjs/modules/script/package.js:191:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by ljuzig** [comment]
Are you sure you installed the latest version?
You said Astra Monitor Version 20, but the latest version is 24 which is fully compatible with GNOME 46 so you shouldn't see any incompatibility warning.
Can you run this command and paste here the output?
`cat ~/.local/share/gnome-shell/extensions/monitor@astraext.github.io/metadata.json`

Here you can get the latest version:
https://extensions.gnome.org/extension/6682/astra-monitor/

**Comment by prog-amateur2** [comment]
So I have tried with version 24 and it still doesn't work (not compatible). I have other extensions that do work well, so I don't know what is the root cause. What do you think ? 

Please find below the logs, thank you very much : 

The settings of extension monitor@astraext.github.io had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:187:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:207:19
start@resource:///org/gnome/gjs/modules/script/package.js:191:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```


### Version check

```
~$ cat ~/.local/share/gnome-shell/extensions/monitor@astraext.github.io/metadata.json
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Astra Monitor is a cutting-edge, fully customizable, and performance-focused system monitoring extension for GNOME's top bar. It's an all-in-one solution for those seeking to keep a close eye on their system's performance metrics like CPU, GPU, RAM, disk usage, network statistics, and sensor readings.",
  "donations": {
    "buymeacoffee": "astra.ext",
    "patreon": "AstraExt"
  },
  "gettext-domain": "monitor@astraext.github.io",
  "license": "GPL-3.0-or-later",
  "name": "Astra Monitor",
  "settings-schema": "org.gnome.shell.extensions.astra-monitor",
  "shell-version": [
    "45",
    "46"
  ],
  "url": "https://github.com/AstraExt/astra-monitor",
  "uuid": "monitor@astraext.github.io",
  "version": 24,
  "version-name": "15"

```

**Comment by ljuzig** [comment]
I just tested on a GNOME 46 VM and it's working out of the box:
![image](https://github.com/AstraExt/astra-monitor/assets/11982322/2e6a4576-b2a9-499e-9fbb-135ac93cd9dc)

Could you check the version of your gnome-shell?
On Fedora 40 I do have `46.0-1.fc40`.
As said, I also tested on 46beta a few weeks ago and everything was fine.

Try to run `apt show gnome-shell` and check what's the GNOME version on your system.
Very likely you have an old beta (or even alpha) version and you have to wait Debian Sid to update to a newer version or update your system.

**Comment by prog-amateur2** [comment]
Bravo, you're right on target! I've been had: 
- the GUI is more or less the same as GNOME 46 (I did notice a few oddities like the `Activities` word on top left bar instead of the new horizontal line) 
- the settings mention GNOME 46
![image](https://github.com/AstraExt/astra-monitor/assets/60101083/17270759-f298-4319-bcc3-e4cfaa2585f4)

- while `apt show gnome-shell` mentions GNOME Version: `44.9-1+b1`  (!!!) : 
```
~$ apt show gnome-shell
Package: gnome-shell
Version: 44.9-1+b1
Priority: optional
Section: gnome
Source: gnome-shell (44.9-1)
```

**Conclusion:** only some of the packages have updated to the GNOME 46 interface, but the shell remains on GNOME 44. So have to be patient. 

Thank you very much for solving this non-bug ! I close it if you don't mind and wish you a very nice week-end.

**Comment by ljuzig** [comment]
Very glad to have been helpful. Thank you, have a nice wekend too!
