### ISSUE TITLE
Hover information position in Network menu not consistent

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#92]
## Description
When moving the mouse to see the on hover information of the _Network_ menu, some pop ups are displayed to the right and some to the left of the menu. This inconsistency makes the menu feel rather confusing and the amount of movement makes you feel dizzy. All on hover information should pop up to the same position, either to the left or right of the menu (not sure how this is decided).

## Steps to Reproduce
1. Install and enable the extension.
2. Click the _Network_ button on the top bar.
3. Move your mouse from top to bottom to see the on hover pop ups.
4. Observe that other pop ups are positioned to the right while other to the left of the menu.

## Screenshots

(Click for full size)

<img src="https://github.com/AstraExt/astra-monitor/assets/16370046/31724158-1dba-4297-ab1a-fd606b85af8f" width="400" />

<img src="https://github.com/AstraExt/astra-monitor/assets/16370046/f0dddd6f-bc44-4c4a-86c4-0acdda0f06b7" width="400" />

<img src="https://github.com/AstraExt/astra-monitor/assets/16370046/d092c885-65c7-4fbd-92ec-d0fe946e7126" width="400" />

<img src="https://github.com/AstraExt/astra-monitor/assets/16370046/35355dc9-479d-4281-8b2b-fe86ee704f40" width="400" />

<img src="https://github.com/AstraExt/astra-monitor/assets/16370046/de23e11e-5674-4648-84a9-7ab66ad046ae" width="400" />

<img src="https://github.com/AstraExt/astra-monitor/assets/16370046/b0126436-30aa-4466-bac3-5c37eaa05476" width="400" />

## Environment
- **Astra Monitor Version**: 16 (EGOv25)
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

**Comment by ljuzig** [comment]
Thank you for reporting, this should be greatly improved in the next release.

**Comment by lepa22** [comment]
You're welcome and thanks for working on it! The issue is resolved in the last update for the case I mentioned, however, it's not solved for every position of the extension.

I tried positioning the extension to the right side of the top bar. If the extension is at the far right of the top bar, I can observe the same issue with the _Processors_ menu. All other items have their pop ups on the left. If the extension is not at the far right of the top bar, it seems that, if there is enough space, some items may display pop ups either to the right or to the left. 

I think that the fix should be similar to the other case: when the extension is positioned to the right, all menus should have their pop ups to the left side.

For the extension positioned in the center, all menus have pop ups to the right, so that works fine.

**Comment by ljuzig** [comment]
It's already like that but it requires the extension to be restarted since the position is setup on popup creation. The popup are created and cached at the extension start for performance reason so the side on where they open is set when the extension start. I wrote that in the release note:
`(Requires the extension to be restarted if the panel box position has been changed in the current sesssion)`
So you may encounter that bug only if you switch the position the first time, whenever you restart the extension or the system it should be fine.

**Comment by lepa22** [comment]
Oh, you're right! I didn't notice the note. Sorry! 🫣
