### ISSUE TITLE
Readings of Network item in the top bar are not entirely inside the rounded rectangle used for highlight

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#93]
## Description
The readings of the _Network_ item in the top bar are not entirely inside the rounded rectangle used for highlight (see screenshot below). More specifically, using the _Show IO Speed_ option for showing the download and upload speeds in the top bar, the upload speed (bottom) lies exactly at the bottom of the rounded rectangle used for highlighting the menu item on hover. Additionally, the unit of the upload speed does not entirely fit the rounded rectangle, and the right-most part of it lies outside of it.

Some padding is required so that the download and upload readings fit symmetrically inside the top bar with respect to the vertical axis and also fit entirely into the rounded rectangle used for highlighting on hover.

## Steps to Reproduce
1. Install and enable the extension.
2. Open the extension's preferences.
3. Go to _Network_ tab &rarr; _IO_ in the _Header_ section &rarr; and toggle _Show IO Speed_ on.
4. Move the mouse to the _Network_ item in the top bar.
5. Observe that the upload reading does not fit correctly inside the rounded rectangle used for highlighting.

## Screenshots
Original screenshot:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/a46972ac-9937-41e0-8f79-0b988f53d15e)

Zoomed-in screenshot:

<img src="https://github.com/AstraExt/astra-monitor/assets/16370046/a46972ac-9937-41e0-8f79-0b988f53d15e" width=300 />

## Environment

- **Astra Monitor Version**: 16 (EGOv25)
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

## Additional Context
Perhaps all items in the top bar need a bit more padding to the left of the icon, as the icons for all items are very close to the edge of the rounded rectangles.

**Comment by ljuzig** [comment]
Just as a test, could you try to set Headers Height and Margins to 26 and 4 respectively and give me a screen of the network IO item on the topbar?
![image](https://github.com/AstraExt/astra-monitor/assets/11982322/a3facddf-e72e-4045-abfc-243253171d68)

The code managing style and layout needs a rewrite to manage different themes that any distro might set to Gnome shell.

**Comment by lepa22** [comment]
Here it is:

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/7948e567-f9ab-4327-8cc5-556b469e14fe)

And zoomed-in:

<img src="https://github.com/AstraExt/astra-monitor/assets/16370046/7948e567-f9ab-4327-8cc5-556b469e14fe" width=300 />

I forgot to mention that the screenshots both in this post and in the main bug report are with the [Just Perfection](https://extensions.gnome.org/extension/3843/just-perfection/) and [Blur my Shell](https://extensions.gnome.org/extension/3193/blur-my-shell/) extensions enabled as well. Just Perfection shrinks the top bar and decrease the font size a bit, while Blur my Shell doesn't really affect anything than the appearance of the top bar and makes the issue more visible. The issue is also there without these extensions, but it's harder to observe.

Additionally, I'm not sure that it's a bug, the _Headers Height_ and _Headers Margins_ options have the same effect: they move the top bar icons up or down. I would expect that this is the case for  _Headers Height_ and that _Headers Margins_ changes the margin inside the on hover rounded box, but that's not so. If you think that this behavior is a bug, I can write another bug report with the issue, so it can be addressed separately.

**Comment by ljuzig** [comment]
They are connected, I think that part needs a overhaul, but it'll require a bit of time so I'm unsure where to place that in the roadmap.

**Comment by lepa22** [comment]
It's not an important functionality issue, it just slightly affects the aesthetics, so you can put it at the end of the roadmap as I see it.
