### ISSUE TITLE
Min and Max CPU values for Astra Monitor are the same in Astra Monitor vs Vitals comparison in COMPARISON.md

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#95]
## Description
Min and Max CPU values for Astra Monitor are the same in [Astra Monitor vs Vitals](https://github.com/AstraExt/astra-monitor/blob/main/COMPARISON.md#astra-monitor-vs-vitals) comparison in [COMPARISON.md](https://github.com/AstraExt/astra-monitor/blob/main/COMPARISON.md).

## Screenshots
> ![image](https://github.com/AstraExt/astra-monitor/assets/16370046/cbdbb422-e463-4010-9462-7ab174230ff3)

**Comment by ljuzig** [comment]
Thank you! This must have been a typo, I should have the full result data at home anyway, I am abroad now. Otherwise I will re-run the test with the latest version, which has some other optimizations and should have an even better result.
