### ISSUE TITLE
network panel displays downward instead of "smart"

### ISSUE THREAD

**Issue by NickBelhomme** [AstraExt/astra-monitor#96]
## Description
The network panel does not show when the panel is at the bottom of the screen.
When the panel is at the top it can show it.

## Steps to Reproduce
I use dash to panel extension to have  a bottom panel, but any bottom panel display extension will result in the same issue.
Once the panel is in the bottom, all icons will show their individual panel overlays vertically upward except network.
Network seems to be always want to be displayed downward instead of upward like the others. Making the information off screen available...

## Environment

- **Astra Monitor Version**: 17 egov27
- **GNOME Version**: 46
- **Operating System and Version**: opensuse thumbleweed

**Comment by ljuzig** [comment]
I have not been able to replicate that. I need you to give me some pointers on how to replicate it. I have enabled Dash-to-Panel and set it to Bottom but Astra is diplayed correctly (see screenshot). How many network connections do you have? Can you provide a screenshot?

![Screenshot from 2024-04-04 15-35-37](https://github.com/AstraExt/astra-monitor/assets/11982322/a85d9131-1327-402d-b984-dbe6e49ca3b8)

**Comment by ljuzig** [comment]
You have too many connections. Looks like Gnome Shell doesn't support popups with anchor point on the bottom when they are higher than the screen size. I will try to find a way to avoid this issue, but in the mean time you can filter your bridges networks setting a regex in the ignore interfaces like this one: `br-\w{8,}`

![image](https://github.com/AstraExt/astra-monitor/assets/11982322/504c7aef-f2a1-4e13-bffe-2f9dfb984ba0)

**Comment by NickBelhomme** [comment]
thx! for the support and the excellent plugin.

**Comment by ljuzig** [comment]
I added a settings that should hint gnome on which side the menu should open:

![image](https://github.com/AstraExt/astra-monitor/assets/11982322/f39953f9-8c41-43f9-b363-d34ec648de7b)
