### ISSUE TITLE
IO Speed text for Storage and Network is varying in size and becomes illegible

### ISSUE THREAD

**Issue by hsiktas** [AstraExt/astra-monitor#97]
## Description

After updating to Beta v18, the displayed text for the current disk and network IO is changing constantly, and it becomes difficult to read. It is also very distracting when I am trying to look at other things on my screen.

## Steps to Reproduce

1. Update to Beta v18 on Ubuntu 23.10 with Gnome 45.2 on X11
2. ???
3. Profit

## Screenshots

[Screencast from 2024-04-07 02-11-33.webm](https://github.com/AstraExt/astra-monitor/assets/4571159/9edc92ba-ae72-45ff-8d30-9320ddda79ea)

## Environment

- **Astra Monitor Version**: Beta v18
- **GNOME Version**: 45.2
- **Operating System and Version**: Ubuntu 23.10
- **Other Relevant System Information**: X11

## Additional Context

I haven't seen this with any previous version, and it was only introduced with this version. The issue remains after rebooting the system.

**Comment by ljuzig** [comment]
I temporarily reversed this until it's fixed, and it will be live as soon as it gets reviewed.

**Comment by ljuzig** [comment]
@hsiktas please update from extensions.gnome.org or from the release in this repo. I kept the layout rendering optimizations but removed the font auto-resize and it should be ok now. Some feedback is appreciated, thank you!

**Comment by hsiktas** [comment]
Thanks. I can confirm that this issue has been fixed. 👍

**Comment by makecraft** [comment]
This still occurs in Beta v20
[Grabación de pantalla desde 2024-04-17 10-37-16.webm](https://github.com/AstraExt/astra-monitor/assets/117121011/754694b0-9b48-4e11-8186-f1c0c8453be2)

**Comment by makecraft** [comment]
> This still occurs in Beta v20 [Grabación de pantalla desde 2024-04-17 10-37-16.webm](https://github.com/AstraExt/astra-monitor/assets/117121011/754694b0-9b48-4e11-8186-f1c0c8453be2)

@ljuzig

**Comment by ljuzig** [comment]
@makecraft It was very likely related to #110 try beta v21

**Comment by makecraft** [comment]
@ljuzig the problem persists in v21

**Comment by ljuzig** [comment]
@makecraft please open a new issue and provide full info about your problem, including your OS, gnome version, etc.. Try to disable all other extensions and record a video of all Astra Monitor's headers. Try to add network speed, storage speed and 2 sensors to see how they behave. Thank you!
